= Using the CQL API

== Prerequisites

To use the CQL API you need:

include::quickstart:page$quick_start.adoc[tag=prereqsList]
* cqlsh (standalone, or as part of a separate Cassandra installation)

include::quickstart:page$quick_start.adoc[tag=getDockerImage]

include::quickstart:page$quick_start.adoc[tag=startDocker]

=== Installing standalone cqlsh using Docker

[source,bash]
----
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' stargate
docker pull nuvo/docker-cqlsh
----

// Use `pip` to install the standalone cqlsh tool.
//
// NOTE: cqlsh requires Python 2.7, and won't work with Python 3.
//
// [source,bash]
// ----
// pip install cqlsh
// ----

== Using the CQL API using cqlsh

Run `cqlsh` from the Docker image.

[source,bash]
----
docker run --rm -it nuvo/docker-cqlsh cqlsh localhost --cqlversion=3.4.5
----

// Connect to the CQL service running locally on port 9042.
//
// [source,bash]
// ----
// cqlsh -u cassandra -p cassandra --cqlversion=3.4.5 localhost 9042
// ----

=== Create a keyspace

Create a keyspace called `users_keyspace`.

[source,sql]
----
CREATE KEYSPACE users_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
----

=== Create a table

[source,sql]
----
CREATE TABLE users_keyspace.users (
    firstname text,
    lastname text,
    email text,
    "favorite color" text,
    PRIMARY KEY (firstname, lastname)
) WITH CLUSTERING ORDER BY (lastname ASC);
----

=== Insert data

[source,sql]
----
INSERT INTO users_keyspace.users (
  firstname,
  lastname,
  email,
  "favorite color"
) VALUES (
  'Mookie',
  'Betts',
  'mookie.betts@gmail.com',
  'blue'
);
----

=== Retrieve data

To select all rows in the table:

[source,sql]
----
SELECT * FROM users_keyspace.users;
----

To select a row using the primary key:

[source,sql]
----
SELECT * FROM users_keyspace.users WHERE firstname = 'Mookie' AND lastname = 'Betts';
----

=== Update data

Update the email address:

[source,sql]
----
UPDATE users_keyspace.users SET email = 'mookie.betts-new-email@gmail.com' WHERE firstname = 'Mookie' AND lastname = 'Betts';
----

Verify that the row has the updated email address:

[source,sql]
----
SELECT * FROM users_keyspace.users WHERE firstname = 'Mookie';
----

=== Delete data

Delete the row using the primary key:

[source,sql]
----
DELETE FROM users_keyspace.users WHERE firstname = 'Mookie' AND lastname = 'Betts';
----

== Using the CQL API with Cassandra drivers

Use the Stargate node as the connection host when connecting using Cassandra drivers.

CAUTION: Do not use the Cassandra nodes as the connection host, only use Stargate nodes.

Stargate can be used with any of the Cassandra drivers:

* https://github.com/datastax/java-driver[Java]
* https://github.com/datastax/csharp-driver[C#]
* https://github.com/datastax/cpp-driver[C++]
* https://github.com/datastax/python-driver[Python]
* https://github.com/datastax/nodejs-driver[Node.js]
* https://github.com/gocql/gocql[Go]

For example, to connect to Stargate running on your local machine using the Python driver:

[source,python]
----
from cassandra.cluster import Cluster

cluster = Cluster(['127.0.0.1'])

session = cluster.connect()

session.set_keyspace('users_keyspace')

rows = session.execute('SELECT firstname, lastname, email FROM users')
for user_row in rows:
    print(user_row.firstname, user_row.lastname, user_row.email)

----
