= Using the Stargate Document API
:docid : 3ffc7ae6-c42d-46de-b52b-b5e77ae6a87b

Stargate is a data gateway deployed between client applications and a database.
The Document API plugin that exposes CRUD access to data stored as unstructured
JSON documents in collections.

If the Document API is used with Apache Cassandra, the document indexing is accomplished
with secondary indexes. If the Document API is used with DataStax Enterprise, SAI indexing
is used. The blog https://stargate.io/2020/10/19/the-stargate-cassandra-documents-api.html[The Stargate Cassandra Documents API]
describes the underlying structure used to store collections.

// tag::prereqsList[]
include::partial$prereqs.adoc[]
// end::prereqsList[]

include::developers-guide:partial$astra_tip.adoc[]

// tag::getDockerImage[]
include::partial$docker_pull.adoc[tag=3x]
// end::getDockerImage[]

// tag::startDocker[]
include::partial$docker_run.adoc[tag=3x]
// end::startDocker[]

// tag::swaggerUI[]
== Swagger UI for the Document API

Once you have started the docker container, you can access the Document API
in a browser at `localhost:8082/swagger-ui`.
Adding parameter information, you can generate `cURL` commands to execute and
display results that will return.
// end::swaggerUI[]

== Using the Auth API to generate an auth token

// tag::GenAuthToken[]
In order to use the Stargate Document API, an authorization token must be
generated to access the interface.

include::partial$gen_auth_token.adoc[]
// end::GenAuthToken[]

// tag::UseAuthToken[]
include::partial$use_auth_token_rest_document.adoc[]
// end::UseAuthToken[]

// tag::UsingPostman[]
== Using Postman

If you prefer, you can use Postman as a client interface for exploring the Document API
(https://www.postman.com/downloads/[download here]).
See xref:ROOT:tooling.adoc[Tooling Resources] for links to downloadable collections and environments.
Instructions for configuring the environments for Stargate OSS and link:https://astra.datastax.com[Astra] are available.
You can immediately import the documentation code examples and explore!
// end::UsingPostman[]

Now you're ready to use the Document API for CRUD operations.

// tag::CreateNS[]
== Creating or dropping a namespace

In order to use the Document API, you must create the namespace as a container
that will store collections, which in turn store documents.
Documents can themselves hold multiple documents.
Multiple collections are contained in a namespace, but a collection cannot be
contained in multiple namespaces.

Only namespaces need to be specifically created. Collections are specified when a document
is inserted. An optional setting, `replicas`, defines
the number of data replicas the database will store for the namespace.
If no replica is defined, then for a namespace in a single datacenter cluster,
the default is 1, and for a multiple-datacenter cluster, the default is 3 for each
datacenter.

=== Creating a namespace

==== Simple namespace

Send a `POST` request to `/v2/schemas/namespaces`.
In this example we use `myworld` for the `name`, and no `replicas` setting, to default to 1.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_simple_ns.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/docapi_curl_create_ns.result[]
----
--
====

The authorization token and the content type are passed with  `--header`. The
token must be identified as `X-Cassandra-Token` so that cluster recognizes the token
and its value.
The specified name for the namespace is passed as JSON data using `--data`.
For shorthand, `cURL` can use `-L` for `--location`, `-X` for `--request`, `-H`
for `--header`, and `-d` for `--data`.
// end::CreateNS[]

// tag::CreateNSextra[]
==== Set replicas in simple namespace

To set the replicas, send a `POST` request to `/v2/schemas/namespaces`.
In this example we use `myworld` for the `name`,
and `2` for the number of data `replicas`.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_create_ns.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/docapi_curl_create_ns.result[]
----
--
====

==== Namespace for multiple datacenters

For a multiple-datacenter cluster, a namespace is defined `datacenters`.
Send a `POST` request to `/v2/schemas/namespaces`.
In this example we use `myworld-dcs` for the `name`, the datacenters are `dc1` and `dc2`,
where `dc1` defaults to 3 replicas and `dc2` is set to 5 replicas.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_ns_dcs.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/docapi_curl_ns_dcs.result[]
----
--
====
// end::CreateNSextra[]

// tag::CheckNS[]
=== Checking namespace existence

To check if a namespaces exist, execute a
Document API query with `cURL` to find all the namespaces:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_check_ns_exists.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/docapi_curl_check_ns_exists.result[]
----
--
====

To get a particular namespace, specify the namespace in the URL:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_get_particular_ns.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/docapi_curl_get_particular_ns.result[]
----
--
====
// end::CheckNS[]

// tag::DeleteNS[]
=== Deleting a namespace

Send a `DELETE` request to `/v2/schemas/namespaces/{namespace_name}` to delete
a namespace. All collections and documents will be deleted along with the
namespace.

[source, bash]
----
include::example$docapi/curl_delete_ns.sh[]
----
// end::DeleteNS[]


// tag::updateColl[]
//== Update or replace a collection

//If you find a collection must be updated or replaced, send a `PUT` request to
//`/v2/schemas/namespaces/{namespace_name}/collections/{collection_name}` with
//the information to change:

//[source, bash]
//----
//curl --location
//--request PUT 'localhost:8082/v2/schemas/namespaces/myworld/collections/fitness'
//--header "X-Cassandra-Token: $AUTH_TOKEN"
//--header 'Content-Type: application/json'
// LLP: PUT IN INFO HERE
//----
// end::updateColl[]

== Interacting with data stored in collections

// tag::WriteBasicData[]
=== Writing documents

All data written with the Document API is stored as JSON documents stored in
collections.

include::partial$DocAPIBlogPost.adoc[]

==== Add document specifying a collection name

First, let's add a document to a specified collection.
Send a `POST` request to `/v2/namespaces/{namespace_name}/collections/{collections_name}`
to add data to the collection `fitness`.
The data is passed in the JSON body.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_post_noDocId.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_post_noDocId.result[]
----
--
====

Notice that the `document-id` returned is a UUID if not specified.

==== Add document specifying collection name and document-id
Next, let's add a document to a specified collection, but specify the `document-id`.
Send a `PUT` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}`
to add data to the collection `Janet`.
The `document-id` can be any string.
The data is passed in the JSON body.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_put_janet.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_put_janet.result[]
----
--
====

Note the difference between using `POST` and `PUT`. The `POST` request
is used to insert new documents when you want the system to auto-generate the
documentId. The `PUT` request is used to insert a new document when you want to
specify the documentId.

`PUT` requests can also be used to update an existing
document. Let's look at those examples, next.

// end::WriteBasicData[]

// tag::WriteAdvData[]
==== Inserting a sub-document
You can also insert documents that have nested values, or sub-documents.
Send a `PUT` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}`
to add data to the existing collection.
The data is passed in the JSON body.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_put_joey_subdoc.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_put_joey_subdoc.result[]
----
--
====
// end::WriteAdvData[]

////
==== Data types???
Need to add data types!!
////

// tag::ReadBasicData[]
=== Reading documents

==== Retrieving all documents
Let's check that the document was inserted. Send a `GET` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}` to retrieve
all the documents:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_get_all_docs.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_get_all_docs.result[]
----
--
====

The `page-size` parameter is included to get all the documents, rather than the
last inserted document.
The `pageState` is useful for pagination of the results in queries.

==== Retrieving a specified document
Let's check that the data was inserted for a particular document.
Send a `GET` request to `/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}`
to retrieve the document:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/curl_get_one_doc.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_get_one_doc.result[]
----
--
====

It is possible to get a value for a particular field in a document using one of
two methods, either a `where` clause or a `document-path`. These methods can
retrieve information from a document or a sub-document.

==== Retrieving a document using a where clause

Now let's search for a particular document using a `where` clause.
Send a `GET` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}?{where-clause}`
to get the same information:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_get_doc_where.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_get_doc_where.result[]
----
--
====

Note that the `where` clause must be url encoded, so curly brackets are escaped
with `\` and spaces must be replaced with `%20`.
Also, the full document is returned, as opposed to the value of the field specified in the
`{document-path}` like the next command.
// end::ReadBasicData[]

// tag::ReadAdvData[]
You can also search with a multiple `where` clause.
Send a `GET` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}?{where-clause}`
to get the same information:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_get_doc_mult_where.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_get_doc_mult_where.result[]
----
--
====

Note that the `where` clause must be url encoded, so curly brackets are escaped
with `\` and spaces must be replaced with `%20`.
Also, the full document is returned, as opposed to the value of the field specified in the
`{document-path}` like the next command.

You can also retrieve documents using a `WHERE` clause that searches sub-documents:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_get_subdoc_where.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_get_subdoc_where.result[]
----
--
====

Multiple `where` can be used in a variety of cases.
Here, a numerical value between to values is sought:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_get_subdoc_mult_where.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_get_subdoc_mult_where.result[]
----
--
====
==== Retrieving a specific portion of a document with document-path

To find a particular value, send a `GET` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}/{document-path}`
to retrieve the type of weights Joey has done in his workout:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_get_joey.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_get_joey.result[]
----
--
====

In this case, the sub-document `weights` is the
`document-path` specified to retrieve that data about the `reps`, `type`, and
`weight`.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_get_joey_weights.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_get_joey_weights.result[]
----
--
====

==== Retrieving a specific portion of a document with json-path

Let's add another record for the next example:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_post_martha.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_post_martha.result[]
----
--
====

To find particular values, send a `GET` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}/{json-path}`
to retrieve all the users that have, say, weight reps between 11 and 16:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_get_json_path_wildcard.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_get_json_path_wildcard.result[]
----
--
====

// end::ReadAdvData[]

// tag::UpdateBasicData[]
=== Update documents

Data changes, so often it is necessary to update an entire document.

==== Replace a document

Send a `PATCH` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}`
to replace data to the existing collection. All fields included will be changed.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_patch_janet.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_janet.result[]
----
--
====

A `GET` request will show that the data has been replaced in the document:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_patch_check_janet.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_check_janet.result[]
----
--
====

NOTE: `PATCH` updates are upserts. If the document doesn't exist, it will be created.
If it does exist, it will be updated with the new document data.

// end::UpdateBasicData[]

// tag::UpdateAdvData[]
==== Replace part of of a document or sub-document

It is also possible to update only part of a document. To partially update, send
a `PATCH` request to
 `/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}/{document-path}`.
In this example, we want to change just the firstname of the document:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_patch_partial.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_partial.result[]
----
--
====

and a `GET` will show that only the `weights` has been changed.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_patch_check_partial.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_check_partial.result[]
----
--
====

To partially update a sub-document,  send a `PATCH` request to
 `/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}/{document-path}`
 in the same manner as the last command, but including only sub-document
 information to change and the `document-path` of the sub-document. Include
 all fields that you wish to update.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_patch_subdoc.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_subdoc.result[]
----
--
====

and a `GET` will show that only the `weights` has been changed.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell]
----
include::example$docapi/curl_patch_check_subdoc.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_check_subdoc.result[]
----
--
====

// end::UpdateAdvData[]

// tag::DeleteBasicData[]
=== Delete a document
To delete a document, send a `DELETE` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}`.

[source,bash, subs="attributes+"]
----
include::example$docapi/curl_delete_doc.sh[]
----
// end::DeleteBasicData[]

// tag::DeleteAdvData[]
To delete a document, based on a document path, send a `DELETE` request to
`/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}/{document-path}`.

[source, bash]
----
include::example$docapi/curl_delete_doc_where.sh[]
----

// tag::deleteColl[]

=== Delete a collection

Send a `DELETE` request to `/v2/schemas/namespaces/{namespace_name}/collections/{collection_name}`
to delete a collection. All data will be deleted along with the collection schema.

[source, bash]
----
include::example$docapi/curl_delete_collection.sh[]
----
// end::deleteColl[]
// end::DeleteAdvData[]
