= Installing Stargate with an existing Cassandra cluster

Stargate can be installed alongside an existing Cassandra cluster.

== Using Stargate with Cassandra 3.11

include::quickstart:page$quick_start.adoc[tag=getDockerImage,leveloffset=+1]

=== Starting Stargate with Cassandra 3.11

Stargate can be added to an existing Cassandra 3.11 cluster operating in a containerized environment in the following way:

[source,bash,subs="attributes+"]
----
docker run --name stargate \
  -d stargateio/stargate-3_11:{stargate-docker-tag} \
  --cluster-name stargate \
  --cluster-seed 127.0.0.1 \
  --cluster-version 3.11 \
  --listen 127.0.0.2 \
  --simple-snitch
----

Where:

* `--cluster-seed` is set to the IP address of a running Cassandra node.
* `--cluster-version` is set to the version of Cassandra running in the cluster.
* `--listen-address` is set to the address on which Stargate will listen.
* `--simple-snitch` sets the snitch on the Stargate node.

NOTE: Use the `--simple-snitch` option if the link:https://github.com/apache/cassandra/blob/cassandra-3.11/conf/cassandra.yaml#L962[endpoint_snitch] setting in the cluster is set to *SimpleSnitch*. If the cluster uses a different `endpoint_snitch` use the `--dc` and `--rack` options to define the topology of the node.

The full set of options are described in xref:starctl.adoc[the `starctl` documentation].

The `--cluster-name` option can alternately be set using `-e` and setting the `CLUSTER_NAME` environment variable to the name of the cluster.

The `--cluster-version` option can alternately be set using `-e` and setting the `CLUSTER_VERSION` environment variable to the version of the cluster.

The `--developer-mode` option can alternately be set using `-e` and setting the `DEVELOPER_MODE` environment variable to `true`.

WARNING: When Stargate is launched within a docker container as shown above, it will connect only to Cassandra clusters running within the same docker environment. To run Stargate so that it can connect to a cluster running outside of a containerized environment, see the link:starctl[starctl] documentation.
>>>>>>> Added warning note about clusters stargate can connect to based on its running environment
