= Using the Stargate GraphQL API

Stargate is a data gateway deployed between client applications and a database.
The GraphQL API plugin that exposes CRUD access to data stored in Cassandra tables.


// tag::prereqsList[]
include::partial$prereqs.adoc[]
// end::prereqsList[]

include::developers-guide:partial$astra_tip.adoc[]

// tag::getDockerImage[]
include::partial$docker_pull.adoc[]
// end::getDockerImage[]

// tag::startDocker[]
include::partial$docker_run.adoc[]
// end::startDocker[]

== Using the Auth API to generate an auth token
In order to use the Stargate Document API, an authorization token must be
generated to access the interface. A REST API token is used for this purpose.

// generate the auth token
include::partial$gen_auth_token.adoc[]

You will need to add this token to the GraphQL Playground in order to authorize
your GraphQL requests. Copy the value after `"authToken"` to use later.

// tag::UseGraphQLPlayground[]
== Using the GraphQL Playground

The easiest way to get started is to use the built-in GraphQL playground that is
included in the `stargate` docker container. It can be accessed at
http://localhost:8080/playground[http://localhost:8080/playground] using a local
browser after the docker container is started.

Once in the playground, you can create new schema and interact with the
GraphQL APIs. The server paths are structured to provide access to creating and
querying schema, as well as querying and modifying Cassandra data:

* `/graphql-schema`
** An API for exploring and creating schema, or Data Definition Language (DDL).
For example, Cassandra has queries to create, modify, drop keyspaces and tables,
such as `CREATE KEYSPACE`, `CREATE TABLE1`, or `DROP TABLE`.
* `/graphql/<keyspace>`
** An API for querying and modifying your Cassandra tables using GraphQL fields.

We'll start the playground with `/graphql-schema` to create some schema.
// end::UseGraphQLPlayground[]

== Creating or dropping schema

In order to use the GraphQL API, you must create schema that defines the keyspace and
tables that will store the data. A keyspace is a container for which a
`replication factor` defines the number of data replicas the database will store.
Tables consist of columns that have a defined data type. Multiple tables are contained
in a keyspace, but a table cannot be contained in multiple keyspaces.

// tag::CreateKS[]
=== Creating a keyspace

Before you can start using the GraphQL API, you must first create a Cassandra
keyspace and at least one table in your database. If you are connecting to a
Cassandra database with existing schema, you can skip this step.

Inside the GraphQL playground, navigate to
http://localhost:8080/graphql-schema[http://localhost:8080/graphql-schema]
and create a keyspace by executing the following mutation:

[source, plaintext]
----
include::example$graphql/createKeyspace.graphql[]
----
For each keyspace created in your Cassandra schema, a new path is created under
the `graphql-path` root (default is: `/graphql`). For example, the mutation just
executed creates a path `/graphql/library` for the `library` keyspace when
Cassandra creates the keyspace.

Add the auth token to the HTTP Headers box in the lower lefthand corner:

[source, plaintext]
----
{
  "x-cassandra-token":"bff43799-4682-4375-99e8-23c8a9d0f304"
}
----

[IMPORTANT]
====
Notice that the key for this JSON token is different than the value that the
generate token has. It is `x-cassandra-token`, not `auth-token`.
====

Now run the mutation to create the keyspace. You should see a return value of:

[source, plaintext]
----
include::example$result/gql_createKeyspace.result[]
----
// end::CreateKS[]

// tag::CreateUDT[]
=== Creating a user-defined type (UDT)

User-defined types (UDTs) can be created and used in table definitions.
This example creates a UDT called `address_type` that includes a street, city, state, and zipcode.

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/createUDT.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_createUDT.result[]
----
--
====

// end::CreateUDT[]

// tag::CreateTable[]
=== Creating a table

After the keyspace exists, you can create two tables by executing the following
mutation:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/createTables.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_createTables.result[]
----
--
====

It is worth noting that one mutation is used to create two tables.
Information about partition keys and clustering keys can be found in the
https://cassandra.apache.org/doc/latest/cql/[CQL reference].

The second table, `reader`, also defines a column using a xref:graphql-using.html#_creating_a_user-defined_type (UDT)[user-defined type (UDT)].

include::partial$GQLNaming.adoc[]
// end::CreateTable[]

==== Data types

// tag::CreateAdvTable[]

Tables can be created with an option `ifNotExists`.
They can also be created with collections (set, list, map), tuples, and UDTs.

==== IF NOT EXISTS option

A table can be created with an option `ifNotExists` that will only create the
table if it does not already exist:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/createTableIfNotExists.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_createTableIfNotExists.result[]
----
--
====

One of these tables includes creating a column with the data type `LIST`, an ordered
collection of text values.
// end::CreateAdvTable[]

==== Collection (set, list, map) columns

Including a collection in a table has a couple of extra parts:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/createMapTable.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_createMapTable.result[]
----
--
====

This example shows a map. A previous example shows a list.
In the next example, a set will be used.

// tag:AddColumns[]
=== Adding columns to table schema

If you need to add more attributes to something you are storing in a table, you
can add one or more columns:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/alterTableAddCols.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_alterTableAddCols.result[]
----
--
====
// end:AddColumns[]

// tag::CheckKSTables[]
=== Checking that keyspaces and tables exist

To check if a keyspace, tables, or particular table columns exist, execute a
GraphQL query:

For keyspaces and tables:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/getKs.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_getKs.result[]
----
--
====

And for tables:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/getTables.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_getTables.result[]
----
--
====

Because these queries are named, the GraphQL playground will allow you to select
which query to run. The first query will return information about the keyspace
`library` and the tables within it. The second query will return just information
about the tables in that keyspace.

// LLP: What about "columns"?

// end::CheckKSTables[]

== Drop keyspaces, user-defined types (UDTs), tables or columns

// tag::DropKS[]
=== Dropping a keyspace

You can delete a keyspace. All tables and table data will be deleted along with
the keyspace schema.

[source, plaintext]
----
include::example$graphql/dropKeyspace.graphql[]
----
// end::DropKS[]

// tag::DropType[]
=== Dropping a type

You can delete a type. All tables that use the UDT must first be deleted.

[source, plaintext]
----
include::example$graphql/dropType.graphql[]
----
// end::DropType[]

// tag::DropTable[]
=== Dropping a table

You can delete a table. All data will be deleted along with the table schema.

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/dropTableArticle.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_dropTableArticle.result[]
----
--
====
// end::DropTable[]

// tag::DropAdvTable[]
==== IF EXISTS option

You can delete a table after checking that it exists with the `ifExists` option.
All data will be deleted along with the table schema.

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/dropTableIfExists.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_dropTableIfExists.result[]
----
--
====
// end::DropAdvTable[]

// tag::DropColumns[]
=== Dropping columns from table schema

If you find an attribute is no longer required in a table, you
can remove a column.  All column data will be deleted along with the column schema.

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/dropColumnFormat.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_dropColumnFormat.result[]
----
--
====
// end::DropColumns[]

== Interacting with data stored in tables

// tag::APIGeneration[]
=== API generation

Once schema is created, the GraphQL API generates mutations and queries can be
used. In the GraphQL playground, expand the tabs on the righthand side labelled
"DOCS" or "SCHEMA", to discover the items available and the syntax to use.

////
For the future, to put in a collapsible section, the portable query is:name: value
query IntrospectionQuery {
      __schema {
        queryType {
          name
          fields {
            name
            description
          }
        }
        mutationType {
          name
          fields {
            name
            description
          }
        }
        subscriptionType { name }
        types {
          ...FullType
        }
        directives {
          name
          description
          locations
          args {
            ...InputValue
          }
        }
      }
    }
​
    fragment FullType on __Type {
      kind
      name
      description
      fields(includeDeprecated: true) {
        name
        description
        args {
          ...InputValue
        }
        type {
          ...TypeRef
        }
        isDeprecated
        deprecationReason
      }
      inputFields {
        ...InputValue
      }
      interfaces {
        ...TypeRef
      }
      enumValues(includeDeprecated: true) {
        name
        description
        isDeprecated
        deprecationReason
      }
      possibleTypes {
        ...TypeRef
      }
    }
​
    fragment InputValue on __InputValue {
      name
      description
      type { ...TypeRef }
      defaultValue
    }
​
    fragment TypeRef on __Type {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                  ofType {
                    kind
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
////

For each table in the Cassandra schema that we just created, several GraphQL
fields are created for
handling queries and mutations. For example, the GraphQL API generated for the
`books` table is:

[source, plaintext]
----
include::example$graphql/generatedApi.graphql[]
----

The query `books()` can query book values by equality. If no value argument is
provided, then the first hundred (default pagesize) values are returned.

Several mutations are created that you can use to insert, update, or delete books.
Some important facts about these mutations are:

* `insertBooks()` is an **upsert** operation if a book with the same information
exist, unless the `ifNotExists` is set to true.
* `updateBooks()` is also an **upsert** operation, and will create a new book if
it doesn't exist, unless `ifNotExists` is set to true.
* Using the `ifNotExists` or `ifCondition` options affects the performance of
operations because of the compare-and-set execution path in Cassandra. Under
the hood these operations are using a feature in Cassandra called lightweight
transactions (LWTs).

As more tables are added to a keyspace, additional GraphQL fields will add
query and mutation types that can be used to interact with the table data.
// end::APIGeneration[]

// tag::WriteData[]
=== Write data

Any of the created APIs can be used to interact with the GraphQL data, to write
or read data.

First, let's navigate to your new keyspace `library` inside the playground.
Change the location to
http://localhost:8080/graphql/library[http://localhost:8080/graphql/library]
and add a couple of books to the `book` table:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/insertTwoBooks.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_insertTwoBooks.result[]
----
--
====

Note that the keyword `value` is used twice in the mutation.
The first use defines the value that the record is set to, for instance, the title
to Moby Dick and the author to Herman Melville. 
The second use defines the values that will be displayed after the success
of the mutation, so that proper insertion can be verified.
This same method is valid for updates and read queries.
// end::WriteData[]

// tag::WriteAdvData[]
==== Insertion options

Three insertion options are configurable during data insertion or updating:

* https://docs.datastax.com/en/dse/6.8/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html[consistency level]
* https://docs.datastax.com/en/dse/6.8/dse-arch/datastax_enterprise/dbInternals/dbIntConfigSerialConsistency.html[serial consistency level]
* https://docs.datastax.com/en/dse/6.8/cql/cql/cql_using/useExpire.html[time-to-live (TTL)]

An example insertion that sets the consistency level and TTL:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/insertBookWithOption.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_insertBookWithOption.result[]
----
--
====

The serial consistency can also be set with `serialConsistency` in the options,
if needed.

==== Insert collections (set, list, map)

Inserting a collection is simple. An example of inserting a list:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/insertArticle.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_insertArticle.result[]
----
--
====

A map is slightly more complex:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/insertOneBadge.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_insertOneBadge.result[]
----
--
====

==== Insert a tuple

Inserting a tuple involves inserting an object; note the use of `item0`, `item`1`,
and so on, to insert the parts of the tuple

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/insertJaneWithTuple.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_insertJaneWithTuple.result[]
----
--
====

==== Insert a user-defined type (UDT)

Inserting a UDT requires taking careful note of the brackets used:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/insertReaderWithUDT.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_insertReaderWithUDT.result[]
----
--
====

// end::WriteAdvData[]

// tag::ReadData[]
=== Read data

Let's check that the data was inserted.

// LLP: Get all book data - add a query

Now let's search for a particular record using a `WHERE` clause. The primary
key of the table can be used in the `WHERE` clause, but non-primary key columns
cannot be used.
The following query, looking at the location
http://localhost:8080/graphql/library[http://localhost:8080/graphql/library]
will get both the `title` and the `author` for the specified book `WHERE
title:"Moby Dick"`:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readOneBook.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readOneBook.result[]
----
--
====

// end::ReadData[]

// tag::ReadAdvData[]

To find multiple books, an addition to the `WHERE` clause is required, to denote that
the list of titles desired is `IN` a group:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readThreeBooks.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readThreeBooks.result[]
----
--
====

To display the contents of a UDT, notice the inclusion of `addresses` in the values displayed for this read query:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readReaderWithUDT.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readReaderWithUDT.result[]
----
--
====

To display the contents of a map collection, notice the inclusion of `earned` in the values displayed for this read query:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readOneGoldBadge.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readOneGoldBadge.result[]
----
--
====
==== Filter options for reading

The filters available are:

* eq (equal)
* notEq (not equal)
* gt (greater than)
* gte (greater than or equal to)
* lt (less than)
* lte (less than or equal to)
* in (within)
* contains (a map contains the specified value)
* containsKey (a map contains the specified key)
* containsEntry (a map contains the specified key:value pair)

Note that these can only be used with primary key columns, just like in Cassandra, unless
indexing is created.

The next examples will query the same table, `badge`, using a variety of filters to illustrate
the versatility of such filters.
The first example finds the record that has the partition key `badge_type` equal to `Gold`, and
the `badge_id` equal to `100`:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readOneGold100Badge.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readOneGold100Badge.result[]
----
--
====

Now if we use a different operator `gt` with the same query, notice that the query will fail,
because no `badge_id` greater than a value of 100 is found:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readOneGoldGT100Badge.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readOneGoldGT100Badge.result[]
----
--
====

In order to use filters for any columns that are not part of the primary key, currently
you need to use CQL to create a secondary index using the CQL shell.
The next three examples show the CQL creation of an index in order to query a column
that is a map collection.

In this example, an index is created on the keys of the map `earned`, so the `containsKey`
filter can be used to query in GraphQL.

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readOneWriterBadge.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readOneWriterBadge.result[]
----
--
====

Because the index now exists, it is also possible to just filter based on the map key itself:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readOneWriterKeyBadge.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readOneWriterKeyBadge.result[]
----
--
====

In this next example, an index is created on the values of the map `earned`, so the `contains`
filter can be used to query in GraphQL.

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readOneWriterValueBadge.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readOneWriterValueBadge.result[]
----
--
====

To make a complete set of filters, an index is created on the entries of the map `earned`, so the `containsEntry`
filter can be used to query in GraphQL.

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/readOneWriterEntryBadge.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_readOneWriterEntryBadge.result[]
----
--
====

// end::ReadAdvData[]

// tag::UpdateData[]
=== Update data

Using the column that we added earlier, the data for a book is updated with the
`ISBN` value:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/updateOneBook.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_updateOneBook.result[]
----
--
====

[NOTE]
====
Updates are upserts. If the row doesn't exist, it will be created.
If it does exist, it will be updated with the new row data.
====
// end::UpdateData[]

// tag::UpdateAdvData[]
It is also possible to update other types of data, such as a set:

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/updateOneBookAgain.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_updateOneBookAgain.result[]
----
--
====
// end::UpdateAdvData[]

// tag::DeleteData[]
=== Delete data

After adding the book "Pride and Prejudice" with an `insertBooks()`, you can delete
the book using `deleteBooks()` to illustrate deleting data:

////
The insertion is:
mutation insertAnotherBook {
  PaP: insertbook(value: {title:"Pride and Prejudice", author:"Jane Austen"}) {
    value {
      title
    }
  }
}
////

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/deleteOneBook.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_deleteOneBook.result[]
----
--
====

Note the use of `ifExists` to validate that the book exists before deleting it.
// end::DeleteData[]

// tag::DeleteAdvData[]
==== Deletion options

Similar to the option `ifExists`, you can delete a book using `consistency`,
`serialConsistency`, or `ttl`, similar to xref:graphql-using.adoc#WriteAdvData[insertions]:

////
The insertion is:
mutation insertAnotherBook {
  PaP: insertbook(value: {title:"Pride and Prejudice", author:"Jane Austen"}) {
    value {
      title
    }
  }
}
////

[tabs]
====
graphQL command::
+
--
[source,shell]
----
include::example$graphql/deleteOneBookCL.graphql[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/gql_deleteOneBookCL.result[]
----
--
====

// end::DeleteAdvData[]

////
I'll need a section that shows how connecting to an existing C* cluster will automatically
create the graphql endpoints!
////
