= GraphQL API

== Overview

The Stargate GraphQL API is implemented to easily modify and query your table data
using GraphQL types, mutations, and queries with any Cassandra deployment.

The Stargate GraphQL API has two orientations, one developed from GraphQL principles, and one developed with the Cassandra Query Language (CQL)
in mind.

include::partial$cql-oriented-desc.adoc[]

include::partial$graphql-oriented-desc.adoc[]

include::partial$compare-orientations.adoc[]

// LLP: I really should put an example side by side of each approach here. For example,
// the reader table as cql-first and as gql-first

include::partial$GQLAPIBlogPost.adoc[]

You can start with a xref:quickstart:quick_start-graphql.adoc[GraphQL QuickStart] or
follow the full instructions: xref:graphql-oriented-using.adoc[[GraphQL oriented]] xref:graphql-using.adoc[[CQL oriented]] .

We'll show you you how to:

// FIX THE REST OF THESE LINKS!
// . xref:generating-authorization-token.adoc[Generate an authorization token]
. xref:manage-application-tokens.adoc[Get an application token]
. Creating a keyspace  xref:developers-guide/graphql-oriented-using.html#_creating_a_keyspace[[GraphQL oriented]]  xref:developers-guide/graphql-using.html#_creating_a_keyspace[[CQL oriented]]
. _Optional_: Creating a user-defined type (UDT)  xref:creating-a-udt-in-your-keyspace-GraphQL-oriented.adoc[[GraphQL oriented]]  xref:creating-a-udt-in-your-keyspace-graphql.adoc[[CQL oriented]]
. Creating table schema  xref:creating-a-table-in-your-keyspace-using-GraphQL-oriented.adoc[[GraphQL oriented]]  xref:creating-a-table-in-your-keyspace-using-graphql.adoc[[CQL oriented]]
. _Optional_: Creating table indexes  xref:creating-an-index-for-a-table-GraphQL-oriented.adoc[[GraphQL oriented]]  xref:creating-an-index-for-a-table-graphql.adoc[[CQL oriented]]
. Deploying schema  xref:deploying-schema-in-your-keyspace-GraphQL-oriented.adoc[[GraphQL oriented]]
. Undeploying schema  xref:undeploying-schema-in-your-keyspace-GraphQL-oriented.adoc[[GraphQL oriented]]
. Dropping user-defined types (UDTs), tables or columns  xref:dropping-schema-graphql.adoc[[CQL oriented]]
. Adding rows to your table  xref:adding-rows-in-your-table-using-GraphQL-oriented.adoc[[GraphQL oriented]]  xref:adding-rows-in-your-table-using-graphql.adoc[[CQL oriented]]
. Retrieving rows from your table  xref:retrieving-rows-in-your-table-using-GraphQL-oriented.adoc[[GraphQL oriented]]  xref:retrieving-rows-in-your-table-using-graphql.adoc[[CQL oriented]]
. Updating rows in your table  xref:updating-rows-in-your-table-using-GraphQL-oriented.adoc[[GraphQL oriented]]  xref:updating-rows-in-your-table-using-graphql.adoc[[CQL oriented]]
. Deleting rows in your table  xref:deleting-rows-in-your-table-using-GraphQL-oriented.adoc[[GraphQL oriented]]  xref:deleting-rows-in-your-table-using-graphql.adoc[[CQL oriented]]

== About the GraphQL API endpoints

There are three Stargate GraphQL API endpoints, one for creating schema in CQL-oriented,
one for deploying schema in the GraphQL-oriented, and the third for querying or mutating a keyspace.
The URLS are:

Schema::
`https://localhost:8080/graphql-schema`
Admin::
`https://localhost:8080/graphql-admin`
Querying::
`https://localhost:8080/graphql/{keyspace_name}`

The schema endpoint is used to create or alter CQL schema in the CQL-oriented GraphQL
using direct schema manipulation.
The admin endpoint is used to deploy GraphQL schema in the GraphQL-oriented GraphQL
which will indirectly modify underlying CQL schema.
The querying endpoint is constructed in the same manner for both GraphQL-oriented and CQL-oriented.

Each request must have a valid xref:manage-application-tokens.adoc[application token].
Each request can also have an optional unique request id.
The request id is recommended in a production environment and can be useful in troubleshooting issues.

[TIP]
====
**Generating UUIDs**
Consider using a tool like this https://www.uuidgenerator.net/[online UUID generator, window="_blank"]
to quickly create a random UUID to pass with your requests if you are submitting
the queries manually using a tool like cURL.
====

include::partial$GQLNaming.adoc[]

// tag::UsingGraphQLPlayground[]
== Using the GraphQL Playground

The easiest way to get started with GraphQL uses the built-in GraphQL playground.
In Astra, go to the Connect tab for your database, choose GraphQL under the
`Connect using an API` and you'll see instructions for accessing the playground.
The GraphQL playground launches the url
`https://localhost:8080/playground`
in your browser.

Add your xref:manage-application-tokens.adoc[application token] to the HTTP HEADERS
section at the lower lefthand corner of the GraphQL Playground window:

{"x-cassandra-token":"$AUTH_TOKEN"}

Once in the playground, you can create new schema and interact with the
GraphQL APIs. The server paths are structured to provide access to creating and
querying schema, as well as querying and modifying Cassandra data:

* `/graphql-schema`
** An API for exploring and creating schema, or Data Definition Language (DDL).
For example, Astra has queries to create, modify, or drop tables,
such as `createTable`, or `dropTable`.
* `/graphql-admin`
** An API for deploying GraphQL schema.
* `/graphql/<keyspace>`
** An API for querying and modifying data in your tables using GraphQL fields.
// end::UsingGraphQLPlayground[]

// tag::UsingPostman[]
== Using Postman

If you prefer, you can use Postman as a client interface for exploring the GraphQL API
(https://www.postman.com/downloads/[download here, window="_blank"]).
We've provided a
https://raw.githubusercontent.com/stargate/docs/master/modules/developers-guide/examples/json/Stargate_GraphQL_API_library_Astra.postman_collection.json[Stargate GraphQL API Postman Astra Collection]
that you can import in Postman to play with the examples shown in this walkthrough.
// end::UsingPostman[]
