== Java querying

A simple query can be performed by passing a CQL query to the client using the
`ExecuteQuery()` function for standard query execution:

[source, go]
----
include::example$java/java-grpc-sync-query.java[]
----

This example is a synchronous, or blocking, interaction.
Interactions with the gRPC API can also be asynchronous (non-blocking):

[source, java]
----
include::example$java/java-grpc-async.java[]
----

Data definition (DDL) queries are supported in the same manner:

[source, go]
----
include::example$java/java-ddl-query.java[]
----

If you would like to use a
link:https://cassandra.apache.org/doc/latest/cassandra/cql/dml.html#batch_statement[batch statement],
the client also provides an `ExecuteBatch()` function to execute a batch query:

[source, java]
----
include::example$java/java-grpc-batch-query.java[]
----

We are adding two queries via the `addQueries` method.
See the link:https://docs.datastax.com/en/dse/6.0/cql/cql/cql_reference/cql_commands/cqlBatch.html[Batch Documentation]
if you want to read more about how the Batch request is handled.

=== More notes on the asynchronous use of the gRPC API

Up to this point, we were using the blocking version of the generated stub.
We can also interact with the Stargate API using the async version of the stub.
To do so, we need to pass the
link:https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html[StreamObserver]
that will be called asynchronously when the results are available.

Every StreamObserver needs to implement 3 methods: `onNext()`, `onError()` and `onComplete()`.
For example:

[source, java]
----
include::example$java/java-grpc-stream-observer.java[]
----

Please note that this is a very simplified version only for demonstration purposes and should not be used on production.

Once we have the Observer, we can pass it to the `executeQuery` method on the async stub:

[source, java]
----
include::example$java/java-grpc-execute-async.java[]
----

This query will return immediately because it is non-blocking.
If your program (or test) is progressing to the end, you may not be able to see the results.
Your program may exit before the data arrives.
After some time, when the data arrives, the `streamObserver` will be called.

The output of our program will look like this:

[source, yaml]
----
include::example$yaml/async-yaml-result.yaml[]
----

Please note, that at the end we have a `completed` emitted.
This is called by the `onCompleted` method.
