== Java querying

Next, we can generate the `StargateGrpc` stub.
There are two ways of interacting with the gRPC API.

The first one is synchronous (blocking):

[source, java]
----
include::example$java/java-grpc-sync.java[]
----

The second one is asynchronous (non-blocking):

[source, java]
----
include::example$java/java-grpc-async.java[]
----

Please note, that we need setup the `CallCredentials`, using the `token-value` generated in the previous step.

We will assume that all queries are executed within the existing keyspace `ks` and table `test`.
The table definition is following:

[source, cql]
----
include::example$cql/java-grpc-create-table.cql[]
----

The Stargate gRPC API provides a way to execute two types of queries:

* standard CQL queries
* batch queries (contains N CQL queries)

=== Standard Query

We can start from inserting a record using gRPC stub:

[source, java]
----
include::example$java/java-grpc-std-query.java[]
----

This will build and execute a single query.

=== Batch Query

In case we want to execute N queries, we can use the `executeBatch` method:

[source, java]
----
include::example$java/java-grpc-batch-query.java[]
----

It takes the `Batch` as an argument.
A Batch can contain N queries of type INSERT, UPDATE, or DELETE.
We are adding two queries via `addQueries` method.
See the link:https://docs.datastax.com/en/dse/6.0/cql/cql/cql_reference/cql_commands/cqlBatch.html[Batch Documentation]
if you want to read more about how the Batch request is handled.

=== Async API

Up to this point, we were using the blocking version of the generated stub.
We can also interact with the Stargate API using the async version of the stub.
To do so, we need to pass the
link:https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html[StreamObserver]
that will be called asynchronously when the results are available.

Every StreamObserver needs to implement 3 methods: `onNext()`, `onError()` and `onComplete()`.
For example:

[source, java]
----
include::example$java/java-grpc-stream-observer.java[]
----

Please note that this is a very simplified version only for demonstration purposes and should not be used on production.

Once we have the Observer, we can pass it to the `executeQuery` method on the async stub:

[source, java]
----
include::example$java/java-grpc-execute-async.java[]
----

This query will return immediately because it is non-blocking.
If your program (or test) is progressing to the end, you may not be able to see the results.
Your program may exit before the data arrives.
After some time, when the data arrives, the `streamObserver` will be called.

The output of our program will look like this:

[source, yaml]
----
include::example$yaml/async-yaml-result.yaml[]
----

Please note, that at the end we have a `completed` emitted. This is called by the `onCompleted` method.
