== Node.js connecting

=== Authentication

This client supports both table-based and JWT-based authentication to Stargate.

For table-based auth, use the `StargateTableBasedToken` class:

[source, javascript]
----
include::example$javascript/node-gen-table-token.js[]
----

For JWT-based auth, use the `StargateBearerToken` class and pass your token in directly:

[source, javascript]
----
include::example$javascript/node-jwt-token.js[]
----

==== Creating a client

If you're connecting to Stargate through insecure gRPC credentials, you must
manually generate metadata for each call
For a local Stargate instance, for instance, the following client code will
fetch an auth token with a REST call:

[source, javascript]
----
include::example$javascript/node-connect-metadata.js[]
----

This is because the Node gRPC implementation
link:https://github.com/grpc/grpc-node/issues/543[does not allow composing insecure credentials.]
However, if you're using secure gRPC credentials, you can include the token
 metadata generator when constructing the client.
For a connection to a remote Stargate instance like link:https://astra.datastax.com[Astra]
automatically generate on every call to the client:

[source, javascript]
----
include::example$javascript/node-client.js[]
----
