== Node.js processing result set

=== Working with responses

A response will contain a `ResultSet` object if you sent CQL that should return data,
or a `SchemaChange` object if your query should have changed the CQL schema.
It will never return both.

If you expect a ResultSet in your response, this library offers a utility method
to convert it for you. You can then read rows, columns and values off the result set:

[source, javascript]
----
include::example$javascript/node-processing1.js[]
----

The `toResultSet` method will never throw an error; it will simply return `undefined`
if it's unable to properly deserialize the value passed to it into a `ResultSet` object.

=== Reading primitive values

Individual values from queries will be returned as a `Value` object.
These objects have boolean `hasX()` methods, where X is the possible type of a value.

There are corresponding `getX()` methods on the `Value` type that will return the value, if present.
If the value does not represent type X, calling `getX()` will not return an error.
You'll get `undefined` or another falsy value based on the expected data type.

[source, javascript]
----
include::example$javascript/node-processing-primitive.js[]
----
