The Apollo data federation directive `@key` defines the fields in an object type
that can be used to uniquely identify an object. It is required for data federation.
In general, this directive can have specific fields identified in a string.
For instance, `@key(fields: "title isbn")` would identify the that the fields
`title` and `isbn` are required to uniquely identify a book.
For Stargate, the presence of the `@key` sets the fields to the primary key,
because Stargate stores data in Apache Cassandra or a Cassandra database like DataStax
Enterprise or Astra DB.

In this example, the following are inferred:

* `Book`: `@key(fields: "title isbn")`
* `Reader`: `@key(fields: "name user_id")`

In GraphQL, standard CamelCase is used for object type names, but Cassandra
requires CamelCase designations to be double-quoted. In order to make the type name
both GraphQL-friendly (`Book`) and CQL-friendly (`book`), a custom directive is used to
identify the Cassandra name (`@cql_entity(name: "book")`) as the identifier of the
underlying table. This directive is not required.

To avoid duplicating the type as both an input type and output type, add `@cql_input`
to generate an `BookInput` type with the same fields as the type `Book`
in the GraphQL schema. This directive is not required, but strongly suggested,
as it is useful for writing queries and mutations.

Similar to the type name, the fields can be identified with an alternative
Cassandra column name using `@cql_column(name: "book_title")`.
This directive is not required.

In the Book type, there are additional `@cql_column` parameters defined to
identify the primary key of the type.
Define the partition key using `@cql_column(partitionKey: true)` for all fields
that comprise the partition key.
Define the clustering columns using `@cql_column(clusteringOrder: ASC)`, for all
the fieldsthat comprise the clustering columns, if desired.
The default clustering order is `ASC`, or ascending.
Information about partition keys and clustering keys can be found in the
https://cassandra.apache.org/doc/latest/cql/[CQL reference].

The `@cql_index` is discussed in xref:graphql-first-using.adoc#_create_indexes[Create indexes].

[IMPORTANT]
====
If no field has a `partitionKey: true`, but the first field is of data type
ID, Uuid, or TimeUuid, then that field is used as the partition key in the database.
====

A standard GraphQL type feature is displayed in these types, the required fields
denoted by `String!` and `Uuid!` that include the exclamation mark.
*** MAKES THEM NON-NULL FIELDS - PARTITION KEY MUST BE NON-NULL!

he `@cql_index` is discussed in xref:graphql-first-using.adoc#_create_indexes[Create indexes].

Lastly, `@cql_column` can be used to provide a hint to Cassandra that specifies
custom field types, such as a set of strings, `@cql_column(typeHint: "set<varchar>")`.
The only valid `typeHints` using a set instead of a list, or making a CQL type frozen.
