= Using the Stargate REST API

Stargate is a data gateway deployed between client applications and a database.
The REST API plugin that exposes CRUD access to data stored in Cassandra tables.

// tag::prereqsList[]
include::partial$prereqs.adoc[]
// end::prereqsList[]

// tag::getDockerImage[]
include::partial$docker_pull.adoc[]
// end::getDockerImage[]

// tag::startDocker[]
include::partial$docker_run.adoc[]
// end::startDocker[]

== Using the Auth API to generate an auth token
In order to use the Stargate Document API, an authorization token must be
generated to access the interface.

// generate the auth token
include::partial$gen_auth_token.adoc[]

// using the auth token
include::developers-guide:page$document-using.adoc[tag=UseAuthToken]

// tag::UsingPostman[]
== Using Postman

If you prefer, you can use Postman as a client interface for exploring REST APIs
(https://www.postman.com/downloads/[download here]).
We've provided a
https://github.com/stargate/docs/blob/master/modules/developers-guide/examples/stargate-rest-api.postman_collection.json[Stargate REST API Postman Collection] that you can import in Postman to play with the examples shown in this walkthrough.

Now you're ready to use the REST API for CRUD operations.
// end::UsingPostman[]

== Creating or dropping schema

In order to use the REST API, you must create schema that defines the keyspace and
tables that will store the data. A keyspace is a container for which a
`replication factor` defines the number of data replicas the database will store.
Tables consist of columns that have a defined data type. Multiple tables are contained
in a keyspace, but a table cannot be contained in multiple keyspaces.

// tag::CreateKS[]
=== Creating a keyspace

Before you can start using the REST API, you must first create a Cassandra
keyspace and at least one table in your database. If you are connecting to a
Cassandra database with existing schema, you can skip this step.

Note that you must create an xref:quickstart/quick_start-rest.adoc#genAuthToken[auth token] first.

Send a `POST` request to `/v2/schemas/keyspaces`.
In this example we use `users_keyspace` for the `name`,
and `1` for the number of data `replicas`.

[source,bash]
----
curl --location --request POST 'localhost:8082/v2/schemas/keyspaces' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "name": "users_keyspace",
    "replicas": 1
}'
----
// end::CreateKS[]

// tag::CreateTable[]
=== Creating a table

Send a `POST` request to `/v2/schemas/keyspaces/{keyspace_name}/tables` to create a table.
Set the table name and column definitions in the JSON body.

[source,bash]
----
curl --location \
--request POST 'localhost:8082/v2/schemas/keyspaces/users_keyspace/tables' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
	"name": "users",
	"columnDefinitions":
	  [
        {
	      "name": "firstname",
	      "typeDefinition": "text"
	    },
        {
	      "name": "lastname",
	      "typeDefinition": "text"
	    },
	    {
	      "name": "email",
	      "typeDefinition": "text"
	    },
        {
	      "name": "favorite color",
	      "typeDefinition": "text"
	    }
	  ],
	"primaryKey":
	  {
	    "partitionKey": ["firstname"],
	    "clusteringKey": ["lastname"]
	  },
	"tableOptions":
	  {
	    "defaultTimeToLive": 0,
	    "clusteringExpression":
	      [{ "column": "lastname", "order": "ASC" }]
	  }
}'
----

Information about partition keys and clustering keys are found in the
https://cassandra.apache.org/doc/latest/cql/[CQL reference].
// end::CreateTable[]

////
==== Data types
Need to add data types!!
////

// tag: AddColumn[]
=== Adding columns to table schema

If you need to add an attribute to something you are storing in a table, you
can add a column by sending a `POST` request to add the column.

[source, bash]
----
curl --location
--request POST 'localhost:8082/v2/schemas/keyspaces/users_keyspace/tables/users/columns/email'
--header 'X-Cassandra-Token: $AUTH_TOKEN'
--header 'Content-Type: application/json'
----

To change the name or data type of an existing column, use a similar command, but
sent a `PUT` request instead:

// LLP: NEED TO CHECK THIS
[source, bash]
----
curl --location
--request PUT 'localhost:8082/v2/schemas/keyspaces/users_keyspace/tables/users/columns/email'
--header 'X-Cassandra-Token: $AUTH_TOKEN'
--header 'Content-Type: application/json'
--data '{
	"name": "email",
	"typeDefinition": "text"
}'
----
// end: AddColumn[]

// tag::CheckKSTables[]
== Checking keyspace, table, and column existence

To check if a keyspace, tables, or particular table columns exist, execute a
REST query with `cURL`:

For keyspaces:

[source,bash]
----
curl -L -X GET 'localhost:8082/v2/schemas/keyspaces' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
// LLP: GET THE RETURN RESULT
["data_endpoint_auth","users_keyspace","stargate_system","system","system_auth","system_distributed","system_schema","system_traces"]
----

To get a particular keyspace:

[source,bash]
----
curl -L -X GET 'localhost:8082/v2/schemas/keyspaces/users_keyspace' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
// LLP: GET THE RETURN RESULT
----

For tables:

[source,bash]
----
curl -L \
-X GET 'localhost:8082/v2/schemas/keyspaces/'users_keyspace'/tables' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
// LLP: GET THE RETURN RESULT
["users"]
----

To get a particular table:

[source,bash]
----
curl -L \
-X GET 'localhost:8082/v2/schemas/keyspaces/'users_keyspace'/tables/users' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
// LLP: GET THE RETURN RESULT
----

For columns:

[source,bash]
----
curl -L \
-X GET 'localhost:8082/v2/schemas/keyspaces/'users_keyspace'/tables/users/columns' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
// LLP: GET THE RETURN RESULT
["users"]
----

To get a particular column:

[source,bash]
----
curl -L \
-X GET 'localhost:8082/v2/schemas/keyspaces/'users_keyspace'/tables/users/columns/email' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
// LLP: GET THE RETURN RESULT
["users"]
----

// end::CheckKSTables[]

== Drop keyspaces, tables or columns

// tag::DropKS[]
=== Dropping a keyspace

Send a `DELETE` request to `/v2/schemas/keyspaces/{keyspace_name}` to delete
a keyspace. All data and all table schema will be deleted along with the
keyspace scheam.

[source, bash]
----
curl --location \
--request DELETE 'localhost:8082/v2/schemas/keyspaces/users_keyspace' \
--header 'X-Cassandra-Token: $AUTH_TOKEN' \
--header 'Content-Type: application/json'
----
// end::DropKS[]

// tag::DropTable[]
=== Dropping a table

Send a `DELETE` request to `/v2/schemas/keyspaces/{keyspace_name}/tables/{table_name}`
to delete a table. All data will be deleted along with the table schema.

[source, bash]
----
curl --location \
--request DELETE 'localhost:8082/v2/schemas/keyspaces/users_keyspace/tables/users' \
--header 'X-Cassandra-Token: $AUTH_TOKEN' \
--header 'Content-Type: application/json'
----
// end::DropTable[]

// tag::RemoveColumn[]
=== Removing columns from table schema

If you find an attribute is no longer required in a table, you
can remove a column by sending a `DELETE` request to delete the column. All
column data will be deleted along with the column schema.

[source, bash]
----
curl --location
--request DELETE 'localhost:8082/v2/schemas/keyspaces/users_keyspace/tables/users/columns/email'
--header 'X-Cassandra-Token: $AUTH_TOKEN'
--header 'Content-Type: application/json'
----
// end::RemoveColumn[]

== Modifying schema

//LLP: need to add "replace a table definition, except for columns"
// which can be used to change table options, like clustering order and TTL

== Interacting with data stored in tables

// tag::WriteData[]
=== Write data

First, let's add some data to the `users` table that you created.
Send a `POST` request to `/v2/keyspaces/{keyspace_name}/{table_name}`
to add data to the table.
The column name/value pairs are passed in the JSON body.

[source,bash]
----
curl --location --request POST 'localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "firstname": "Mookie",
    "lastname": "Betts",
    "email": "mookie.betts@gmail.com",
    "favorite color": "blue"
}'
curl --location --request POST 'localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "firstname": "Janesha",
    "lastname": "Doesha",
    "email": "janesha.doesha@gmail.com",
    "favorite color": "grey"
}'
----
// end::WriteData[]

// tag::ReadData[]
=== Read data

Let's check that the data was inserted. Send a `GET` request to
`/v2/keyspaces/{keyspace_name}/{table_name}` to retrieve all the data:

[source,bash]
----
curl GET \
--location 'http://localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
----

Now let's search for a particular record using a `WHERE` clause. The primary
key of the table can be used in the `WHERE` clause, but non-primary key columns
cannot be used.
Send a `GET` request to `/v2/keyspaces/{keyspace_name}/{table_name}`
to retrieve the row for `Mookie`:

[source,bash]
----
curl GET \
--location 'http://localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data-urlencode 'where={"firstname": {"$eq": "Mookie"}}'
----
// end::ReadData[]

// tag::UpdateData[]
=== Update data

Data changes, so often it is necessary to update an entire row.
To update a row, send a `PUT` request to `/v2/keyspaces/{keyspace_name}/{table_name}/{path}`.
The `{path}` is comprised of the primary key values.
In this example, the partition key is `firstname` "Mookie" and the
clustering key is `lastname` "Betts";
thus, we use `/Mookie/Betts` as the `{path}` in our request.

[source,bash]
----
curl --location \
--request PUT 'localhost:8082/v2/keyspaces/users_keyspace/users/Mookie/Betts' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "email": "mookie.betts.new-email@email.com"
}'
----

NOTE: Updates are upserts. If the row doesn't exist, it will be created.
If it does exist, it will be updated with the new row data.

// end::UpdateData[]

It is also possible to update only part of a row. To partially update, send
a `PATCH` request to   `/v2/keyspaces/{keyspace_name}/{table_name}/{path}`.
In this example, we realize we should not have changed the email address, and
we want to only change that one column:

[source,bash]
----
curl --location \
--request PATCH 'localhost:8082/v2/keyspaces/users_keyspace/users/Mookie/Betts' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "email": "mookie.betts.email@email.com"
}'
----

// tag::DeleteData[]
=== Delete data
To delete a row, send a `DELETE` request to
`/v2/keyspaces/{keyspace_name}/{table_name}/{path}`.
In this request we delete all data with the primary key `firstname` of `Mookie`:

[source,bash]
----
curl --location \
--request DELETE 'localhost:8082/v2/keyspaces/users_keyspace/users/Mookie' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json'
----
// end::DeleteData[]
