= Using the Stargate REST API

Stargate is a data gateway deployed between client applications and a database.
The REST API plugin that exposes CRUD access to data stored in Cassandra tables.

// tag::prereqsList[]
include::partial$prereqs.adoc[]
// end::prereqsList[]

// tag::getDockerImage[]
include::partial$docker_pull.adoc[]
// end::getDockerImage[]

// tag::startDocker[]
include::partial$docker_run.adoc[]
// end::startDocker[]

// tag::swaggerUI[]
=== Swagger UI for the REST API

Once you have started the docker container, you can access the REST API
in a browser at `localhost:8082/swagger-ui`.
Adding parameter information, you can generate `cURL` commands to execute and
display results that will return.
// end::swaggerUI[]

== Using the Auth API to generate an auth token
In order to use the Stargate REST API, an authorization token must be
generated to access the interface.

// generate the auth token
include::partial$gen_auth_token.adoc[]

// using the auth token
include::developers-guide:page$document-using.adoc[tag=UseAuthToken]

// tag::UsingPostman[]
== Using Postman

If you prefer, you can use Postman as a client interface for exploring REST APIs
(https://www.postman.com/downloads/[download here]).
We've provided a
https://github.com/stargate/docs/blob/master/modules/developers-guide/examples/stargate-rest-api.postman_collection.json[Stargate REST API Postman Collection] that you can import in Postman to play with the examples shown in this walkthrough.

Now you're ready to use the REST API for CRUD operations.
// end::UsingPostman[]

// tag::CreateKS[]
== Creating or dropping keyspace and table schema

In order to use the REST API, you must create schema that defines at least one
keyspace and one table that will store the data.
A keyspace is a container for which a `replication factor` defines the number of
data replicas the database will store.
Tables consist of columns that each have a name and a defined data type.
Multiple tables are contained in a keyspace, but a table cannot be contained in
multiple keyspaces.
If you are connecting to a Cassandra database with existing schema, you can skip
this step.

For keyspaces, an optional setting, `replicas`, defines
the number of data replicas the database will store for the keyspace.
If no replica is defined, then for a keyspace in a single datacenter cluster,
the default is 1, and for a multiple-datacenter cluster, the default is 3 for each
datacenter.

=== Creating a keyspace

==== Simple keyspace

Send a `POST` request to `/v2/schemas/keyspaces`.
In this example we use `user_keyspace` for the `name`, and no `replicas` setting, to default to 1.

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_simple_ks.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_create_ks.result[]
----
--
====

The authorization token and the content type are passed with  `--header`. The
token must be identified as `X-Cassandra-Token` so that cluster recognizes the token
and its value.
The specified name for the keyspace is passed as JSON data using `--data`.
For shorthand, `cURL` can use `-L` for `--location`, `-X` for `--request`, `-H`
for `--header`, and `-d` for `--data`.
// end::CreateKS[]

//tag::CreateKSextra[]
==== Set replicas in simple keyspace

Send a `POST` request to `/v2/schemas/keyspaces`.
In this example we use `users_keyspace` for the `name`,
and `1` for the number of data `replicas`.

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_create_ks.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_create_ks.result[]
----
--
====

==== Keyspace for multiple datacenters

For a multiple-datacenter cluster, a keyspace is defined `datacenters`.
Send a `POST` request to `/v2/schemas/keyspaces`.
In this example we use `users_keyspace-dcs` for the `name`, the datacenters are `dc1` and `dc2`,
where `dc1` defaults to 3 replicas and `dc2` is set to 5 replicas.

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_ks_dcs.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_ks_dcs.result[]
----
--
====
[source,bash]
----
include::example$bash/rest_curl_ks_dcs.sh[]
----
// end::CreateKSextra[]

// tag::CheckKS[]
=== Checking keyspace existence

To check if a keyspaces exist, execute a
REST API query with `cURL` to find all the keyspaces:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_check_ks_exists.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_check_ks_exists.result[]
----
--
====

To get a particular keyspace, specify the keyspace in the URL:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_get_particular_ks.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_get_particular_ks.result[]
----
--
====
// end::CheckKS[]

// tag::CreateTable[]
=== Creating a table

Send a `POST` request to `/v2/schemas/keyspaces/{keyspace_name}/tables` to create a table.
Set the table name and column definitions in the JSON body.

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_create_table.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_create_table.result[]
----
--
====

Information about partition keys and clustering keys are found in the
https://cassandra.apache.org/doc/latest/cql/[CQL reference].
// end::CreateTable[]

////
==== Data types
Need to add data types!!
////

// tag: AddColumn[]
=== Adding columns to table schema

If you need to add an attribute to something you are storing in a table, you
can add a column by sending a `POST` request to add the column.

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_add_column.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_add_column.result[]
----
--
====

To change the name or data type of an existing column, use a similar command, but
sent a `PUT` request instead:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_change_column.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_change_column.result[]
----
--
====

// end: AddColumn[]

// tag::CheckTables[]
== Checking table and column existence

To check if a table exists, execute a
REST API query with `cURL` to find all the tables:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_check_table_exists.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_check_table_exists.result[]
----
--
====

To get a particular table, specify the table in the URL:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_get_particular_table.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_get_particular_table.result[]
----
--
====

To check if a column exists, execute a
REST API query with `cURL` to find all the columns:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_check_column_exists.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_check_column_exists.result[]
----
--
====

To get a particular column, specify the column in the URL:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_get_particular_column.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/rest_curl_get_particular_column.result[]
----
--
====
// end::CheckTables[]

== Drop keyspaces, tables or columns

// tag::DropKS[]
=== Dropping a keyspace

Send a `DELETE` request to `/v2/schemas/keyspaces/{keyspace_name}` to delete
a keyspace. All data and all table schema will be deleted along with the
keyspace scheam.

[source, bash]
----
include::example$bash/rest_curl_drop_ks.sh[]
----
// end::DropKS[]

// tag::DropTable[]
=== Dropping a table

Send a `DELETE` request to `/v2/schemas/keyspaces/{keyspace_name}/tables/{table_name}`
to delete a table. All data will be deleted along with the table schema.

[source, bash]
----
include::example$bash/rest_curl_drop_table.sh[]
----
// end::DropTable[]

// tag::RemoveColumn[]
=== Removing columns from table schema

If you find an attribute is no longer required in a table, you
can remove a column by sending a `DELETE` request to delete the column. All
column data will be deleted along with the column schema.

[source, bash]
----
include::example$bash/rest_curl_drop_column.sh[]
----
// end::RemoveColumn[]

== Modifying schema

//LLP: need to add "replace a table definition, except for columns"
// which can be used to change table options, like clustering order and TTL

== Interacting with data stored in tables

All data written with the REST API is stored in columns in tables that were
specified with the schema.

// tag::WriteData[]
=== Write data

First, let's add some data to the `users` table that you created.
Send a `POST` request to `/v2/keyspaces/{keyspace_name}/{table_name}`
to add data to the table.
The column name/value pairs are passed in the JSON body.

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_write_users.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/rest_curl_write_users.result[]
----
--
====

[NOTE]
====
Notice that, unlike schema creation, data queries do not require `tables` in the
URI, only the `{tableName}`.
====
// end::WriteData[]

// tag::ReadData[]
=== Read data

Let's check that the data was inserted. Send a `GET` request to
`/v2/keyspaces/{keyspace_name}/tables/{table_name}` to retrieve the two users
that were entered:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_get_users.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/rest_curl_get_users.result[]
----
--
====

This query uses `$in` to find the two users.
The `WHERE` clause can be used with other valid search terms: `$eq`, `$lt`,
`$lte`, `$gt`, `$gte`, `$ne`, and `$exists`, if applicable.
The primary key of the table can be used in the `WHERE` clause, but non-primary
key columns cannot be used.
Send a `GET` request to `/v2/keyspaces/{keyspace_name}/{table_name}`
to retrieve the row for `Mookie` using `$eq`:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_get_users_where.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/rest_curl_get_users_where.result[]
----
--
====
// end::ReadData[]

// tag::UpdateData[]
=== Update data

Data changes, so often it is necessary to update an entire row.
To update a row, send a `PUT` request to `/v2/keyspaces/{keyspace_name}/{table_name}/{path}`.
The `{path}` is comprised of the primary key values.
In this example, the partition key is `firstname` "Mookie" and the
clustering key is `lastname` "Betts";
thus, we use `/Mookie/Betts` as the `{path}` in our request.

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_update_users.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/rest_curl_update_users.result[]
----
--
====

[NOTE]
====
Updates are upserts. If the row doesn't exist, it will be created.
If it does exist, it will be updated with the new row data.
====
// end::UpdateData[]


// LLP: The update PUT and the PATCH do the same thing. I need to figure out
// the difference.
It is also possible to update only part of a row. To partially update, send
a `PATCH` request to   `/v2/keyspaces/{keyspace_name}/{table_name}/{path}`.
In this example, we realize we should not have changed the email address, and
we want to only change that one column:

[tabs]
====
cURL command::
+
--
[source,shell]
----
include::example$bash/rest_curl_patch_users.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/rest_curl_patch_users.result[]
----
--
====

// tag::DeleteData[]
=== Delete data
To delete a row, send a `DELETE` request to
`/v2/keyspaces/{keyspace_name}/{table_name}/{primaryKey}`.
For this example, the primary key consists of a partition key `firstname` and
clustering column `lastname`, so we delete all data with `Mookie/Betts`:

[source,bash]
----
include::example$bash/rest_curl_delete_row.sh[]
----
// end::DeleteData[]
