== Rust set-up

=== Prerequisites

* xref:authnz.adoc[Get an application token]
* Create a table in your keyspace: xref:rest-using.adoc#_create_a_keyspace[(REST)]  xref:graphql-first-using.adoc#_create_a_keyspace[(GraphQL)]
* xref:start-stargate.adoc[Start Stargate (optional)]

=== Set up a Rust project

. Use the following command to initialize a Rust project in an empty directory:

[source, rust]
----
include::example$rust/rust-init.rs[]
----

Two files will be created, `Cargo.toml` and `src/main.rs`.

=== Add dependencies

. Add required dependencies to the `Cargo.toml` file in your Rust project.
You'll need at least `stargate-grpc` and an async framework, such as link:https://tokio.rs/[tokio]:
+
[source, rust]
----
include::example$rust/rust-setup-dependencies.rs[]
----
// LLLP: The stargate version may need to be changed.
+
. Build the project with `cargo build` and fetch and compile the dependencies.
+
. Add the following line to the includes in the source code of your app, such as `main.rs`:
+
[source, rust]
----
include::example$rust/rust-setup-use.rs[]
----

This set-up will make all the Stargate gRPC functionality available.

The next sections explain the parts of a script to use the Stargate functionality.
A xref:gRPC-rust-client.adoc#_rust_full_sample_script[full working script] is included below.
