= How to contribute to Stargate docs
:asciidoc-syntax-url: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
:antora-platform-url: https://docs.antora.org/
//:bpg-url: https://github.com/stargate/docs/blob/master/docs/best-practices.md

We welcome all helpful contributions to the Stargate documentation, whether they’re reporting issues, adding new material, or modifying what exists.

If you wish to contribute to the repository, you must:

* First, have a https://github.com/[GitHub] account.
* Second, fork the official repositories, write your material, and create a pull request. 

The Stargate documentation is written in the {asciidoc-syntax-url}[AsciiDoc file format]
and is powered by the {antora-platform-url}[Antora documentation platform].

When contributing to the documentation, please follow our {bpg-url}[Best Practices and Tips guide].

* The documentation is in https://github.com/stargate/docs/[the stargate/docs repository on GitHub].
  Read https://github.com/stargate/docs/blob/master/docs/getting-started.md[the documentation] for instructions on 
  setting up your build environment and becoming familiar with the file format and the build system that powers the documentation.

== Reporting Documentation Errors

If you find errors or omissions in the documentation, we encourage you to report them. 
Please follow this template when reporting documentation errors:

. First, search the respective repository for matching or similar issues.
. If an issue is not available, open a new one.
. Link to the error that you want to see fixed. 
. Quote the particular error.
. Provide the correct solution (if you know it) and any links to supporting references. 
  If you don't know the answer that is OK.
. Provide screenshots if they add useful information.

== Reporting Documentation Suggestions

If you don't have a specific problem or contribution, open an issue to offer a suggestion.
