= Tooling Resources
:slug: resources

== Postman resources

=== Prerequisite

* Install https://www.postman.com[Postman] to run postman testing

Postman is a widely-used collaboration platform for API development and testing.
Using this third-party tool, you can easily test APIs with environments generated
for your test platforms and imported testing collections of API queries.

Postman collections are comprised of REST, Document, or GraphQL schema and queries
to run or test against one or more defined environments.
The tool includes a https://learning.postman.com/docs/running-collections/intro-to-collection-runs/[collection runner testing utility]
for testing against query assertions embedded in the collection.
Collections and environments can be https://learning.postman.com/docs/getting-started/importing-and-exporting-data/[imported or exported]
with Postman.

For Stargate development, three collections that correspond to the documentation code examples are available:

* https://github.com/stargate/docs/blob/main/modules/developers-guide/examples/json/Stargate-OSS-Astra-REST-API-users_keyspace.postman_collection.json[REST collection]
* https://github.com/stargate/docs/blob/main/modules/developers-guide/examples/json/Stargate-OSS-Astra-Document-API-myworld.postman_collection.json[Document collection]
* https://github.com/stargate/docs/blob/main/modules/developers-guide/examples/json/Stargate-OSS-Astra-GraphQL-API-library.postman_collection.json[GraphQL collection]

Each collection lets you try out creation, insertion, and deletion of both data and schema, as required.

To use the collections, you'll need to download and configure a postman environment.
Two environments are also available, one for the open-source Stargate docker image and one for https://astra.datastax.com[DataStax Astra].
A small amount of configuration is necessary in the single environment to set your
parameters before use.

* https://github.com/stargate/docs/blob/main/modules/developers-guide/examples/json/Stargate%20Astra%20API%20Environment.postman_environment.json[Astra environment]
* https://github.com/stargate/docs/blob/main/modules/developers-guide/examples/json/Stargate%20OSS%20API%20Environment.postman_environment.json[Stargate OSS environment]

=== Postman environment configuration

==== Stargate OSS

If you are using non-standard ports, you'll need to
https://learning.postman.com/docs/sending-requests/managing-environments/[change them in the Postman environment].
You can also edit the JSON file directly, if you prefer.

==== Astra

There are three items that must be
https://docs.datastax.com/en/astra/docs/manage-application-tokens.html[retrieved from the Astra dashboard] and configured in the Postman environment:

* ASTRA_DB_ID
* ASTRA_DB_REGION
* ASTRA_DB_APPLICATION_TOKEN

Open the https://learning.postman.com/docs/sending-requests/managing-environments/[environment in Postman]
and copy/paste in the appropriate values.
You can also edit the JSON file directly, if you prefer.

== BloomRPC resources

=== Prerequisite

* Install https://github.com/bloomrpc/bloomrpc#installation[BloomRPC] to run gRPC testing

BloomRPC aims to provide the simplest and most efficient developer experience for
exploring and querying your GRPC services.
Using this third-party tool, you can easily test gRPC proto files with environments generated
for your test platforms.

For instance, the proto files can be
https://github.com/stargate/stargate/tree/master/grpc-proto/proto[imported into BloomRPC].
Select `ExecuteQuery` from the imported files.
Set the environment to `localhost:8090` if running a Stargate docker container.
In the metadata, add an authentication token with `{"x-cassandra-token": "<auth_token>"}`.
If you have followed one of the xref:gRPC-using.adoc[gRPC client] instructions,
add the following query and push the run button:

[source, plaintext]
----
{
  "cql": "SELECT * FROM users",
  "values": {
    "type": 0
  },
  "parameters": {
    "keyspace": {
      "value": "test"
    }
  }
}
----

You should get the same results from the database table that you received running
command-line tools.
