= Include examples and partials
:url-docs-antora: https://docs.antora.org/antora/2.3
:url-docs-adoc: https://asciidoctor.org/docs/user-manual
:url-resource: {url-docs-antora}/page/resource-id/
:url-include-example: {url-docs-antora}/asciidoc/include-example/
:url-include-partial: {url-docs-antora}/asciidoc/include-partial/
:url-include-page: {url-docs-antora}/asciidoc/include-page/
:url-tags: {url-docs-adoc}/#by-tagged-regions
:url-indent: {url-docs-adoc}/#normalize-block-indentation
:url-leveloffset: {url-docs-adoc}/#include-partitioning

== Example files

Examples are non-AsciiDoc files that contain reusable content, such as source code
or programmatic output, that is often inserted into xref:code-blocks.adoc[code blocks].
They're saved in the xref:component-configuration.adoc#examples-dir[_examples_ directory of a module].
Regardless of an example's source module, it can be inserted into any standard
page in your documentation site using the include directive and the example file's resource ID.

.Include directive and example resource ID structure:

[source, plaintext]
----
\include::version@component:module:example$file.ext[]
----

== Partial files

Partials are AsciiDoc files that contain reusable snippets of content.
They're saved in the xref:component-configuration.adoc#partials-dir[_partials_ directory of a module].
Regardless of a partial's source module, it can be inserted into any standard page
in your documentation site using the include directive and the partial file's resource ID.

.Include directive and partial resource ID structure:

[source, plaintext]
----
\include::version@component:module:partial$file.adoc[]
----

== Insert an example or a partial

An entire example or partial (or a portion of) is inserted into a page using the
include directive and file's resource ID.
A {url-resource}[resource ID^] is just like a page ID, but it has an extra coordinate, `family$`.
The family coordinate for examples is `example$` and `partial$` for partials.
Like the xref:cross-references.adoc[page ID in an xref], the more a page and
the partial or example are related, the less coordinates you have to specify.

.Include from the same module:

[source, plaintext]
----
\include::example$result/gql_getKs.result[]

\include::partial$astra_tip.adoc[]
----

.Include from the same component, different modules:

[source, plaintext]
----
\include::ROOT:example$random.java[]

\include::developers-guide:partial$docker_run.adoc.adoc[]
----

.Include from different components:

[source, plaintext]
----
\include::4.5@tree::example$extension.js[]

\include::catalog::partial$ref/definitions.adoc[]
----

[#tag-region]
== Insert tagged content from an example or partial

To include a snippet of content from an example or partial (instead of the whole file), use the `tag` directive.

.Tagging content in a partial file:

[source, plaintext]
----
// tag::CreateKS[] <1> <2>
=== Create a keyspace

Before you can start using the GraphQL API, you must first create a Cassandra
keyspace in your database. The keyspace is a container that stores data
with replication.

// end::CreateKS[]<3> <4>
----
<1> To indicate the start of a tagged region, insert a comment line (`+//+`) in the file.
<2> Assign a unique name to the region in the `tag` directive, followed by a set of square brackets (`[]`).
In this example the tag is called _CreateKS_.
<3> Insert a comment line where you want the tagged region to end.
<4> Assign the name of the region you want to terminate to the `end` directive.

To insert a tagged region into a page, enter the resource ID and tag attribute in the include directive.

.Include a tagged region of a partial into a page in another component:

[source, plaintext]
----
// create keyspace
\include::developers-guide:page$rest-using.adoc[tag=CreateKS]
----

Code regions in example files can be tagged using the language's comment syntax before `tag` and `end`.
For example, if you tag code in a YAML file, place a hash (`+#+`) before the tag directive.

[source,yaml]
----
# tag::expire[]
  artifacts:
    expire_in: 1 week
# end::expire[]
    paths:
    - public/
----

// LLP 10.08.21 Need to decide on developer preview partial and whether it would be useful
== Stargate Documentation Partials

=== Developer preview partial

To call out a section of a page as Developer Preview, use the `developer-preview` partial.
Otherwise if the whole page is Developer Preview content, you can use the
xref:attributes-and-roles.adoc#custom-page-attributes[page-status] attribute.

----
\include::home:ROOT:partial$developer-preview.adoc[]
----

Renders as:

include::home:ROOT:partial$developer-preview.adoc[]

== Learn more

* xref:code-blocks.adoc#include-code[Insert examples into code blocks with the include directive].
* Browse the source files in the SDK language and common components on GitHub for numerous examples of partial includes and tagging.

== Additional resources

The Antora and Asciidoctor documentation provide more information about including partials, examples, and standard pages as well as optional attributes such as `indent` and `leveloffset`.

* {url-resource}[Antora resource ID structure^]
* {url-include-example}[Insert examples with the include directive^]
* {url-include-partial}[Insert partials with the include directive^]
* {url-include-page}[The page-partial attribute and inserting a standard page with the include directive^]
* {url-tags}[Select code regions with the tag directive^]
* {url-indent}[Normalize block indentation with the indent attribute^]
* {url-leveloffset}[Offset section headings with leveloffset^]
