= Send Your Changes for Review

After you complete your changes and fixed any warnings and errors reported by Antora, it's time to commit and push your working branch to your remote repository.

[#commit]
== Commit, Rebase, and Push

. Add the new and changed files.

 $ git add file-path-and-name

. Commit your changes.

 $ git commit -m "fix graphql example"

. Fetch any upstream base branch changes.

 $ git fetch upstream name-of-base-branch

. If the upstream base branch has changed, rebase your working branch against it.

 $ git rebase upstream/name-of-base-branch

. Push your working branch to your remote fork on GitHub.

 $ git push origin name-of-pr-branch

[#pr]
== Submit a Pull Request

After you push your working branch to your remote repository on GitHub, you can submit a pull request to the upstream repository for review.

. Go to your repository on GitHub, and click btn:[Compare & pull request].
. On the Open a Pull Request screen, update the PR title if it needs clarification, and then click btn:[Create Pull Request].

Your pull request will be reviewed by a member of the Stargate documentation team.
Feedback and suggestions for improvements to the pull request are a standard part of the process, to ensure consistency across the documentation.
Response will normally be within a couple of working days, but can sometimes take longer -- please bear with us, we really do appreciate contributions from the community.

== Submit a Review

To review an existing pull request, use GitHub's Pull Request Review features:

. https://help.github.com/en/articles/reviewing-proposed-changes-in-a-pull-request#starting-a-review[Starting a Review^]
. https://help.github.com/en/articles/reviewing-proposed-changes-in-a-pull-request#marking-a-file-as-viewed[Marking a File as Viewed^]
. https://help.github.com/en/articles/reviewing-proposed-changes-in-a-pull-request#submitting-your-review[Submitting your Review^]

== Incorporate Feedback from a Review

To incorporate feedback from a review of an existing pull request, use GitHub's https://help.github.com/en/articles/incorporating-feedback-in-your-pull-request#applying-suggested-changes[Applying Suggested Changes^] instruction page.

== Next Step

Learn how AsciiDoc xref:asciidoc-overview.adoc[is used for Stargate documentation].
