= API References

Stargate  provides APIs to manage database resources.

== Stargate

Stargate provides multiple APIs to connect to your database:

* link:_attachments/docv2.html[Stargate Document API v2]: The Stargate Document API allows you to use schemaless storage of free-form JSON Documents in your database. Get examples of using the Document API in the xref:develop:dev-with-doc.adoc[Developing with Stargate/Document API] section.
* link:_attachments/restv2.html[Stargate REST API v2]: The Stargate REST API allows you to perform standard CRUD operations on your data using a simple, cross-language interface. Get examples of using the REST API v2 in the xref:develop:dev-with-rest.adoc[Developing with Stargate/REST API] section.

The xref:develop:graphql.adoc[Stargate GraphQL API] allows you to easily interact with your data using GraphQL types, queries, and mutations. For every table in your keyspace, a series of GraphQL objects are generated, along with queries and mutations that allow you to search and modify the table data. Get examples of using the GraphQL API in the xref:develop:graphql.adoc[Developing your application/GraphQL API] section.

=== Older versions

* link:_attachments/restv1.html[Stargate REST API v1]
