= Frequently asked questions

:page-tag: stargate,dev,develop,planner

== What should I do if I find a bug?

- If you've found an issue while using Stargate, please file a bug in the
https://github.com/stargate/stargate[Stargate repo] and use the bug label.
It's also helpful to include the full stack trace and the Stargate and database
version that you are using so that we can efficiently debug.
- If you've found an issue with the documentation, please file an issue in the
https://github.com/stargate/docs[Stargate docs repo]. Pull requests are also
accepted!

== Why should I use Stargate when I already have an existing database?

Stargate provides APIs, data types and access methods that bring new capabilities
to existing databases.
Currently Stargate adds both REST and GraphQL APIs for CRUD access to data stored
in Apache Cassandra(R) and there are many more APIs coming soon.
Separating compute and storage also has benefits for maximizing resource
consumption in cloud environments.
When using Stargate with Cassandra, you can offload the request coordination
overhead from your storage instances onto Stargate instances
which has shown latency improvements in preliminary testing (results coming soon).

== How can I get involved?

To get started building a new API extension, have a look at the existing
https://github.com/stargate/stargate/tree/master/restapi[REST API implementation]
or the https://github.com/stargate/stargate/tree/master/graphqlapi[GraphQL API implementation]
in the Stargate repo first. To get started building a new storage extension,
check out the
https://github.com/stargate/stargate/tree/master/persistence-cassandra-3.11[persistence-cassandra-3.11 implementation].
Once you have an idea of what you want to build, shoot us a note on the
https://github.com/stargate/stargate/discussions[Github discussion page] to discuss.

**Note** that the internal APIs are under active development and they are
likely to change before the first version is released.
