= Stargate documentation

This repo contains the source files for the Stargate documentation.

The docs are written in asciidoc and use Antora to generate the output.

The Stargate docs are organized into three Antora modules:

* The ROOT module, with general project infomation.
* A quickstart module, with basic documentation to get new users started.
* The developers-guide module with more extensive topics on all the features of Stargate.

== Generating and viewing HTML output

The current development version of the docs are at https://stargate.github.io/docs/.

A GitHub action will generate and publish the development docs on pushes to the master branch. Development docs use the `site-local.yaml` Antora site configuration file.

Pushing a tag starting with `v` will trigger a publish action that generates the docs and publishes them to the `stargate/website` repo in the `gh-pages` branch. Live docs use the `site-publish.yaml` Anotra site configuration file. 

To generate the docs locally during development:

[source,bash]
----
antora --stacktrace --clean site-local.yaml
----

Open the files in a web browser to view the output.

== Reporting bugs

File a https://github.com/stargate/docs/issues[GitHub issue] or let us know in our https://groups.google.com/a/lists.stargate.io/g/stargate-users[Google group].
