=== Start the Stargate container

// tag::3x[]
.v2
[%collapsible%open]
===== 
Use this docker-compose https://github.com/stargate/stargate/blob/v2.0.0/docker-compose/cassandra-3.11/start_cass_311_dev_mode.sh[shell script] to start the coordinator and APIs in developer mode.
The easiest way to do that is to navigate to the `<install_location>/stargate/stargate/docker-compose` directory, and run the script.
You will want to run, for example:

[source,bash,subs="attributes+"]
----
./start_cass_{cass-alt-tag-3x}_dev_mode.sh -t {stargate2-docker-tag}
----

The latest available image can be found https://hub.docker.com/r/stargateio/coordinator-3_11/tags[here].
=====

.v1
[%collapsible%]
=====
Start the Stargate container in xref:install:starctl.adoc[developer mode].
Developer mode removes the need to set up a separate Cassandra instance and is
meant for development and testing only.

[source,bash,subs="attributes+"]
----
docker run --name stargate \
  -p 8080:8080 \
  -p 8081:8081 \
  -p 8082:8082 \
  -p 127.0.0.1:9042:9042 \
  -d \
  -e CLUSTER_NAME=stargate \
  -e CLUSTER_VERSION={cass-tag-3x} \
  -e DEVELOPER_MODE=true \
  stargateio/stargate-{cass-alt-tag-3x}:{stargate-docker-tag-3x}
----
=====
// end::3x[]

// tag::40[]
.v2
[%collapsible%open]
===== 
Use this docker-compose https://github.com/stargate/stargate/blob/v2.0.0/docker-compose/cassandra-4.0/start_cass_40_dev_mode.sh[shell script] to start the coordinator and APIs in developer mode.
The easiest way to do that is to navigate to the `<install_location>/stargate/stargate/docker-compose` directory, and run the script.
You will want to run, for example:

[source,bash,subs="attributes+"]
----
./start_cass_{cass-alt-tag-40}_dev_mode.sh -t {stargate2-docker-tag}
----

The latest available image can be found https://hub.docker.com/r/stargateio/coordinator-4_0/tags[here].
=====

.v1
[%collapsible%]
=====
Start the Stargate container in xref:install:starctl.adoc[developer mode].
Developer mode removes the need to set up a separate Cassandra instance and is
meant for development and testing only.

[source,bash,subs="attributes+"]
----
docker run --name stargate \
  -p 8080:8080 \
  -p 8081:8081 \
  -p 8082:8082 \
  -p 127.0.0.1:9042:9042 \
  -d \
  -e CLUSTER_NAME=stargate \
  -e CLUSTER_VERSION={cass-tag-40} \
  -e DEVELOPER_MODE=true \
  stargateio/stargate-{cass-alt-tag-40}:{stargate-docker-tag-40}
----
=====
// end::40[]

// tag::dse_68[]
.v2
[%collapsible%open]
===== 
Use this docker-compose https://github.com/stargate/stargate/blob/v2.0.0/docker-compose/dse-6.8/start_cass_40_dev_mode.sh[shell script] to start the coordinator and APIs in developer mode.
The easiest way to do that is to navigate to the `<install_location>/stargate/stargate/docker-compose` directory, and run the script.
You will want to run, for example:

[source,bash,subs="attributes+"]
----
./start_dse_{dse-alt-tag-68}_dev_mode.sh -t {stargate2-docker-tag}
----

The latest available image can be found https://hub.docker.com/r/stargateio/coordinator-6.8/tags[here].
=====

.v1
[%collapsible%]
=====
Start the Stargate container in xref:install:starctl.adoc[developer mode].
Developer mode removes the need to set up a separate DSE instance and is
meant for development and testing only.

[source,bash,subs="attributes+"]
----
docker run --name stargate \
  -p 8080:8080 \
  -p 8081:8081 \
  -p 8082:8082 \
  -p 127.0.0.1:9042:9042 \
  -d \
  -e CLUSTER_NAME=stargate \
  -e CLUSTER_VERSION={dse-tag-68} \
  -e DEVELOPER_MODE=true \
  stargateio/stargate-dse-{dse-alt-tag-68}:{stargate-docker-tag-68}
----
=====
// end::dse_68[]

// tag::3x_graphql-first[]
This method is not required for Stargate v2, but you need these instructions for Stargate v1.
Start the Stargate container in xref:install:starctl.adoc[developer mode].
Developer mode removes the need to set up a separate Cassandra instance and is
meant for development and testing only.

[source,bash,subs="attributes+"]
----
docker run --name stargate \
  -p 8080:8080 \
  -p 8081:8081 \
  -p 8082:8082 \
  -p 127.0.0.1:9042:9042 \
  -d \
  -e CLUSTER_NAME=stargate \
  -e CLUSTER_VERSION={cass-tag-3x} \
  -e DEVELOPER_MODE=true \
  -e JAVA_OPTS="-Dstargate.graphql_first.enabled=true" \
  stargateio/stargate-{cass-alt-tag-3x}:{stargate-docker-tag-3x}
----
// end::3x_graphql-first[]

// tag::grpc[]
This method is not required for Stargate v2, but you need these instructions for Stargate v1.
If you don't already have access to a Stargate deployment, one can be started
quickly for testing in xref:install:starctl.adoc[developer mode].
Developer mode removes the need to set up a separate Cassandra instance and is
meant for development and testing only.
This `docker run` command also exposes port 8090 for gRPC connections.

[source,bash,subs="attributes+"]
----
docker run --name stargate \
  -p 8080:8080 \
  -p 8081:8081 \
  -p 8082:8082 \
  -p 8090:8090 \
  -p 127.0.0.1:9042:9042 \
  -d \
  -e CLUSTER_NAME=stargate \
  -e CLUSTER_VERSION={cass-tag-40} \
  -e DEVELOPER_MODE=true \
  stargateio/stargate-{cass-alt-tag-40}:{stargate-docker-tag-40}
----

Ensure the local instance of Stargate is running properly by tailing the logs for the container,
and looking for the message that indicates Stargate is ready for traffic.

[tabs]
====
shell command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$bash/docker-logs.sh[]
----
--

Result::
+
--
[source,plaintext]
----
include::example$result/sh_docker-logs.result[]
----
--
====
// end::grpc[]
