=== Pull the Docker image

// tag::3x[]
.v2
[%collapsible%open]
=====
For Stargate v2, you'll need to pull an image for coordinator, plus an image for each API that you wish to run: restapi, graphql, and docsapi. 
The coordinator image contains a Apache Cassandra^(TM)^ backend, the Cassandra Query Language (CQL), and the gRPC API.

The following are the commands for each of those images:

[source,bash,subs="attributes+"]
----
docker pull stargateio/coordinator-{cass-alt-tag-3x}:{stargate2-docker-tag}
docker pull stargateio/restapi:{stargate2-docker-tag}
docker pull stargateio/docsapi:{stargate2-docker-tag}
docker pull stargateio/graphql:{stargate2-docker-tag}
----
=====

.v1
[%collapsible%]
=====
This image contains the Cassandra Query Language (CQL), REST, Document, GraphQL APIs,
and GraphQL Playground, along with an Apache Cassandra^(TM)^ {cass-tag-3x} backend.

[source,bash,subs="attributes+"]
----
docker pull stargateio/stargate-{cass-alt-tag-3x}:{stargate-docker-tag-3x}
----
=====
// end::3x[]

// tag::40[]
.v2
[%collapsible%open]
=====
For Stargate v2, you'll need to pull an image for coordinator, plus an image for each API that you wish to run: restapi, graphql, and docsapi. 
The coordinator image contains a Apache Cassandra^(TM)^ backend, the Cassandra Query Language (CQL), and the gRPC API.

The following are the commands for each of those images:

[source,bash,subs="attributes+"]
----
docker pull stargateio/coordinator-{cass-alt-tag-40}:{stargate2-docker-tag}
docker pull stargateio/restapi:{stargate2-docker-tag}
docker pull stargateio/docsapi:{stargate2-docker-tag}
docker pull stargateio/graphql:{stargate2-docker-tag}
----
=====

.v1
[%collapsible%]
=====
This image contains the Cassandra Query Language (CQL), REST, Document, GraphQL APIs,
and GraphQL Playground, along with an Apache Cassandra^(TM)^ {cass-tag-40} backend.

[source,bash,subs="attributes+"]
----
docker pull stargateio/stargate-{cass-alt-tag-40}:{stargate-docker-tag-40}
----
=====
// end::40[]

// tag::dse_68[]
.v2
[%collapsible%open]
=====
For Stargate v2, you'll need to pull an image for coordinator, plus an image for each API that you wish to run: restapi, graphql, and docsapi. 
The coordinator image contains a Apache Cassandra^(TM)^ backend, the Cassandra Query Language (CQL), and the gRPC API.

The following are the commands for each of those images:

[source,bash,subs="attributes+"]
----
docker pull stargateio/coordinator-{dse-alt-tag-68}:{stargate2-docker-tag}
docker pull stargateio/restapi:{stargate2-docker-tag}
docker pull stargateio/docsapi:{stargate2-docker-tag}
docker pull stargateio/graphql:{stargate2-docker-tag}
----
=====

.v1
[%collapsible%]
=====
This image contains the Cassandra Query Language (CQL), REST, Document, GraphQL APIs,
and GraphQL Playground, along with a DataStax Enterprise^(TM)^  {dse-tag-68} backend.

[source,bash,subs="attributes+"]
----
docker pull stargateio/stargate-dse-{dse-alt-tag-68}:{stargate-docker-tag-68}
----
=====
// end::dse_68[]
