= Using the CQL API

To use Stargate's Cassandra Query Language (CQL) API you can use the same CQL
syntax, tools and native language drivers that you would with a normal
Cassandra deployment.

Popular Cassandra drivers are:

* https://github.com/datastax/java-driver[Java]
* https://github.com/datastax/csharp-driver[C#]
* https://github.com/datastax/cpp-driver[C++]
* https://github.com/datastax/python-driver[Python]
* https://github.com/datastax/nodejs-driver[Node.js]
* https://github.com/gocql/gocql[Go]
* https://spring.io/projects/spring-data-cassandra[Spring Data Cassandra]

ifeval::["{product}" == "Stargate"]
[NOTE]
====
When using Cassandra drivers with Stargate you must:

. Use the addresses of the Stargate instances as contact points rather than the
addresses of the Cassandra storage instances.
. Use the Round Robin policy in the driver for the
https://docs.datastax.com/en/devapp/doc/devapp/driversLoadBalancing.html[Load Balancing Policy]
rather than the Token Aware Policy.
====
endif::[]

== Prerequisites

* cqlsh (CQL shell) (standalone, as part of Astra DB, or as part of a separate Cassandra installation)
include::develop:partial$prereqs-astra.adoc[]
include::develop:partial$prereqs-stargate.adoc[]

== Accessing the CQL API using cqlsh

ifeval::["{database}" == "Astra DB"]
include::connect:page$connecting-to-astra-databases-using-cqlsh.adoc[]
endif::[]

ifeval::["{database}" == "Stargate"]
=== Installing a standalone cqlsh using Docker

Install a standalone cqlsh docker image to access Stargate. First, pull the
following docker image:

[source, shell, subs="attributes+"]
----
docker pull nuvo/docker-cqlsh
----
Get the IP address of your Stargate docker container (assuming the Stargate
 container name is "stargate"). This command assumes the stargate docker
 container is running:

[source, shell, subs="attributes+"]
----
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' stargate
----

Connect to your Stargate container using `cqlsh` using the IP address from the
last command:

[source, shell, subs="attributes+"]
----
docker run --rm -it nuvo/docker-cqlsh cqlsh {ip-address} --cqlversion=3.4.5
----

Now you are ready to interact with Cassandra!
endif::[]

== Interact with CQL

You can now add and retrieve schema and data using CQL.


ifeval::["{database}" == "Stargate"]
=== Create a keyspace

Create a keyspace called `users_keyspace`.

[source,sql]
----
CREATE KEYSPACE users_keyspace
  WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}
  AND durable_writes = true;
----
endif::[]

=== Create a table

[source,sql]
----
CREATE TABLE users_keyspace.users (
    firstname text,
    lastname text,
    email text,
    "favorite color" text,
    PRIMARY KEY (firstname, lastname)
) WITH CLUSTERING ORDER BY (lastname ASC);
----

=== Insert data

[source,sql]
----
INSERT INTO users_keyspace.users (
  firstname,
  lastname,
  email,
  "favorite color"
) VALUES (
  'Mookie',
  'Betts',
  'mookie.betts@gmail.com',
  'blue'
);
----

=== Retrieve data

To select all rows in the table:

[source,sql]
----
SELECT * FROM users_keyspace.users;
----

To select a row using the primary key:

[source,sql]
----
SELECT * FROM users_keyspace.users WHERE firstname = 'Mookie' AND lastname = 'Betts';
----

=== Update data

Update the email address:

[source,sql]
----
UPDATE users_keyspace.users SET email = 'mookie.betts-new-email@gmail.com' WHERE firstname = 'Mookie' AND lastname = 'Betts';
----

Verify that the row has the updated email address:

[source,sql]
----
SELECT * FROM users_keyspace.users WHERE firstname = 'Mookie';
----

=== Delete data

Delete the row using the primary key:

[source,sql]
----
DELETE FROM users_keyspace.users WHERE firstname = 'Mookie' AND lastname = 'Betts';
----

== Using the CQL API with Cassandra drivers

{product} can be used with any of the Cassandra drivers. 
ifeval::["{product}" == "Stargate"]
Use the Stargate node as the contact point when connecting using Cassandra drivers, and use the https://docs.datastax.com/en/devapp/doc/devapp/driversLoadBalancing.html[Round Robin load balancing policy].
endif::[]

For example, to connect to {datastax} running on your local machine using the Python driver, replacing the IP address with an appropriate address:

[source,python]
----
from cassandra.cluster import Cluster

cluster = Cluster(['127.0.0.1'])

session = cluster.connect()

session.set_keyspace('users_keyspace')

rows = session.execute('SELECT firstname, lastname, email FROM users')
for user_row in rows:
    print(user_row.firstname, user_row.lastname, user_row.email)

----
