= Developing with the {database} Document API
:keywords: database, document, api

include::develop:partial$stargate-intro-intro.adoc[]
The Stargate Document API modifies and queries data stored as unstructured JSON documents in collections.
Because the Document API uses schemaless data, no data modeling is required!

If the Document API is used with Apache Cassandra, document indexing is accomplished with https://cassandra.apache.org/doc/trunk/cassandra/cql/indexes.html[Cassandra secondary indexes].

// LLP 07.25.2022 Add a link to SAI when it is added and published in the CQL doc. 

If the Document API is used with DataStax Enterprise, SAI indexing is used. 
The blog https://stargate.io/2020/10/19/the-stargate-cassandra-documents-api.html[The Stargate Cassandra Documents API] describes the underlying structure used to store collections.

== Information about namespaces and collections.

To use the Document API, you must define a namespace that will store  collections.
Collections store unstructured JSON documents.
Documents can themselves hold multiple documents.
Multiple collections are contained in a namespace, but a collection cannot be
contained in multiple namespaces.

Only namespaces need to be specifically created.
Collections are specified when a document is inserted.

== Prerequisites

include::develop:partial$prereqs-astra.adoc[]
include::develop:partial$prereqs-stargate.adoc[]

== API reference

If you prefer to learn using a QuickStart, try out the xref:quickstart:qs-document.adoc[Stargate Document QuickStart, window="_blank"].
To view the API Reference, see xref:develop:attachment$docv2.html[{database} Document API, window="_blank"].

// NAMESPACES
// STARGATE ONLY
ifeval::["{product}" == "Stargate"]
include::develop:page$api-doc/doc-namespace-creating.adoc[Creating a namespace, leveloffset=+1]
endif::[]

include::develop:page$api-doc/doc-namespace-checking.adoc[Checking namespaces, leveloffset=+1]

// STARGATE ONLY
ifeval::["{product}" == "Stargate"]
include::develop:page$api-doc/doc-namespace-deleting.adoc[Deleting a namespace, leveloffset=+1]
endif::[]

// COLLECTIONS
include::develop:page$api-doc/doc-collection-creating.adoc[Creating a collection, leveloffset=+1]

include::develop:page$api-doc/doc-collection-checking.adoc[Checking collections, leveloffset=+1]

include::develop:page$api-doc/doc-collection-deleting.adoc[Deleting a collection, leveloffset=+1]

// DOCUMENTS
include::develop:page$api-doc/doc-writing-documents.adoc[Writing documents, leveloffset=+1]

include::develop:page$api-doc/doc-updating-documents.adoc[Updating documents, leveloffset=+1]

// ACTUALLY NEED SEARCH COLLEcTIONS FOR DOCUMENTs BEFORE SEARCHING/READING IN DOCUMENTS

include::develop:page$api-doc/doc-reading-documents.adoc[Reading documents, leveloffset=+1]

include::develop:page$api-doc/doc-document-deleting.adoc[Deleting documents, leveloffset=+1]

// MOVE THIS STUFF TO SDKs and create a page there.
//include::develop:page$api-doc/doc-nodejs-client.adoc[Node.js Collection Client]
