== Using the GraphQL Playground

The easiest way to get started with GraphQL is to use the built-in GraphQL playground.
ifeval::["{product}" == "Astra DB"]
In {database}, go to the Connect tab for your database, choose GraphQL under the
`Connect using an API` and you'll see instructions for accessing the playground.
The GraphQL playground launches the url:
`{base_graphql_url}/api/playground`
in your browser.
endif::[]
ifeval::["{product}" == "Astra DB Serverless"]
In {database}, go to the Connect tab for your database, choose GraphQL under the
`Connect using an API` and you'll see instructions for accessing the playground.
The GraphQL playground launches the url:
`{base_graphql_url}/api/playground`
in your browser.
endif::[]
ifeval::["{product}" == "Astra DB for DSE"]
In {database}, go to the Connect tab for your database, choose GraphQL under the
`Connect using an API` and you'll see instructions for accessing the playground.
The GraphQL playground launches the url:
`{base_graphql_url}/api/playground`
in your browser.
endif::[]
ifeval::["{product}" == "Stargate"]
In {database}, go to your browser and launch the url:
`{base_graphql_url}/playground`
endif::[]

Add your 
ifeval::["{product}" == "Astra DB"]
xref:manage:org/manage-tokens.adoc#manage-application-tokens[application token]
endif::[]
ifeval::["{product}" == "Astra DB Serverless"]
xref:manage:org/manage-tokens.adoc#manage-application-tokens[application token]
endif::[]
ifeval::["{product}" == "Astra DB for DSE"]
xref:manage:org/manage-tokens.adoc#manage-application-tokens[application token]
endif::[]
ifeval::["{product}" == "Stargate"]
xref:secure:authnz.adoc#table-based-authenticationauthorization[application token]
endif::[] 
to the HTTP HEADERS
section at the lower lefthand corner of the GraphQL Playground window:
[source, plaintext, sub="attributes+"]
----
{"x-cassandra-token":"$AUTH_TOKEN"}
----

Once in the playground, you can create new schema and interact with the
GraphQL APIs. The server paths are structured to provide access to creating and
querying schema, as well as querying and modifying Cassandra data:

* `{base_gql_schema}`
** An API for exploring and creating schema, or Data Definition Language (DDL).
For example, {database} has queries to create, modify, or drop tables,
such as `createTable`, or `dropTable`.
* `{base_gql_api}/<keyspace>`
** An API for querying and modifying your tables using GraphQL fields.
Generally, you will start the playground with `{base_gql_schema}` to create some schema.
