
// tag::Directives[]
== Directives

[cols="20h,~,~"]
|===
| Name | Description | Arguments
| @cql_column | Set type field CQL values
a|
name: String

partitionKey: true/false

clusteringOrder: ASC/DESC

typeHint: String
| @cql_delete | Conditional delete clause, with possible consistency level, serial consistency level, or targetEntity
a|
if Exists: true/false

consistencyLevel: MutationConsistency = ALL/LOCAL_ONE/LOCAL_QUORUM

serialConsistency: SerialConsistency = LOCAL_SERIAL/SERIAL

targetEntity: String
| @cql_entity | Set a type field data type
a|
name: String

target (UDT)
| @cql_increment | Set a type field that will increment on UPDATE
a|
field to increment (counter, set, and list only): String

The default is false, meaning that the value will be appended

prepend: Boolean = false
| @cql_if | Set a type field that the predicate `if <field> <predicate` uses to check condition for  DELETE and UPDATE.
a|
field: String
predicates (EQ, GT, GTE, IN, GT, LTE, and NEQ)
| @cql_index | Create a type field index
a|
name: String

class: (org.apache.cassandra.index.sasi.SASIIndex)

type: (FULL, VALUES)

options: (mode: 'CONTAINS')

target: String
| @cql_input | Identify a type as an input type | name (optional): String
| @cql_insert | Add a conditional clause, consistency level, serial consistency level, or time-to-live (TTL)
a|
ifNotExists: true/false

consistencyLevel: MutationConsistency = ALL/LOCAL_ONE/LOCAL_QUORUM

serialConsistency: SerialConsistency = LOCAL_SERIAL/SERIAL

ttl: String (interpreted in seconds)
| @cql_pagingState | The paging state to inject in the query | N/A
| @cql_payload | Identify a type as a payload type | N/A
| @cql_select | Set response arguments pageSize, limit, with possible consistencyLevel
a|
consistencyLevel: QueryConsistency = ALL/LOCAL_ONE/LOCAL_QUORUM/LOCAL_SERIAL/SERIAL

pageSize: Int

limit: Int
| @cql_update | Set an insertion to be an update, with possible conditional clause, consistency level, serial consistency level, time-to-live (TTL), or targetEntity
a|
ifExists: true/false

consistencyLevel: MutationConsistency = ALL/LOCAL_ONE/LOCAL_QUORUM

serialConsistency: SerialConsistency = LOCAL_SERIAL/SERIAL

ttl: String (interpreted in seconds)

targetEntity: String
| @cql_where | Predicates that customize the conditions of a parameter
a|
field: String

predicate (EQ (default), GT, GTE, IN, LT, LTE, CONTAINS)
|===

include::partial$curl_cql_directive.adoc[]
// end::Directives[]