// tag::CreateKS[]
== Create or delete keyspace and table schema

In order to use the REST API, you must create schema that defines at least one
keyspace and one table that will store the data.
A keyspace is a container for which a `replication factor` defines the number of
data replicas the database will store.
Tables consist of columns that each have a name and a defined data type.
Multiple tables are contained in a keyspace, but a table cannot be contained in
multiple keyspaces.
If you are connecting to a Cassandra database with existing schema, you can skip
this step.

For keyspaces, an optional setting, `replicas`, defines
the number of data replicas the database will store for the keyspace.
If no replica is defined, then for a keyspace in a single datacenter cluster,
the default is 1, and for a multiple-datacenter cluster, the default is 3 for each
datacenter.

=== Create a keyspace

==== Simple keyspace

Send a `POST` request to `{base_rest_schema}`.
In this example we use `{rkeyspace}` for the `name`, and no `replicas` setting, to default to 1.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$rest/curl_simple_ks.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/rest_curl_create_ks.result[]
----
--
====

The authorization token and the content type are passed with  `--header`. The
token must be identified as `X-Cassandra-Token` so that cluster recognizes the token
and its value.
The specified name for the keyspace is passed as JSON data using `--data`.
For shorthand, `cURL` can use `-L` for `--location`, `-X` for `--request`, `-H`
for `--header`, and `-d` for `--data`.
// end::CreateKS[]

//tag::CreateKSextra[]
==== Set replicas in simple keyspace

Send a `POST` request to `{base_rest_schema}`.
In this example we use `{rkeyspace}` for the `name`,
and `1` for the number of data `replicas`.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$rest/curl_create_ks.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/rest_curl_create_ks.result[]
----
--
====

==== Keyspace for multiple datacenters

For a multiple-datacenter cluster, a keyspace is defined `datacenters`.
Send a `POST` request to `{base_rest_schema}`.
In this example we use `{rkeyspace-dcs}` for the `name`, the datacenters are `dc1` and `dc2`,
where `dc1` defaults to 3 replicas and `dc2` is set to 5 replicas.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$rest/curl_ks_dcs.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/rest_curl_ks_dcs.result[]
----
--
====
// end::CreateKSextra[]