= Stargate

== Quick Links

[cols=",",options="header",]
|===
|What |Where
|Community |Chat with us on
https://discord.gg/YJ7vheE[Discord]

|===

== Features

== Version Compatibility

[cols=",,,,,",options="header",]
|===
|Stargate |Cassandra |DSE
|0.1 |4.0 |6.8
|===

== Download

// == Building
//
// See xref:developers-guide:building_and_artifacts.adoc[Building And Artifacts]

== Documentation

* xref:quickstart:quick_start.adoc[Quick-start guide]
// * xref:developers-guide:connecting.adoc[Developer's Guide]
* xref:FAQ.adoc[FAQ]

== Community

=== Reporting Bugs

New issues may be reported using https://github.com/stargate/docs/issues[GitHub Issues]. Please include all relevant details including versions of Stargate and Cassandra and/or DSE. A minimal reproducible case with sample code is ideal.

== Questions, comments, and feedback

Go to our https://discord.gg/YJ7vheE[Discord channel] to discuss Stargate with the community.

== Contributing

== Testing

== License

This project uses the https://github.com/stargate/docs/blob/master/LICENSE[Apache 2.0 license].
