= 5-minute quick start guide for Stargate

Stargate is a data gateway deployed between client applications and a database.
In this quickstart, you'll be up and running on your local machine with the REST API
plugin that exposes CRUD access to data stored in Cassandra tables.

== Prerequisites

To use Stargate you need:

// tag::prereqsList[]
* Docker
* JDK 8 or later
* `cURL` to run REST queries
// end::prereqsList[]

// == Building Stargate
//
// In a terminal:
//
// . Clone the https://github.com/stargate/stargate repository:
//
// [source,bash]
// ----
// git clone https://github.com/stargate/stargate
// ----
//
// . Navigate to the `stargate` directory.
//
// [source,bash]
// ----
// cd stargate
// ----
//
// . Build Stargate using the `mvnw` command.
//
// [source,bash]
// ----
// ./mvnw clean package
// ----

// tag::getDockerImage[]
== Pull the Docker image

This image contains the Cassandra Query Language (CQL) and REST APIs with an Apache Cassandra(R) 3.11 backend.

[source,bash,subs="attributes+"]
----
docker pull stargateio/stargate-3_11:{stargate-docker-tag}
----

// end::getDockerImage[]

// tag::startDocker[]
== Start the container

Start the Stargate container in developer mode.
Developer mode removes the need to set up a separate Cassandra instance and is meant for dev/testing only.

[source,bash,subs="attributes+"]
----
docker run --name stargate \
  -p 8081:8081 \
  -p 8082:8082 \
  -p 127.0.0.1:9042:9042 \
  -d \
  -e CLUSTER_NAME=stargate \
  -e CLUSTER_VERSION=3.11 \
  -e DEVELOPER_MODE=true \
  stargateio/stargate-3_11:{stargate-docker-tag}
----

By default, Stargate starts a CQL service on port 9042,
a REST auth service for generating tokens on 8081,
and a REST interface for CRUD on port 8082.

// end::startDocker[]

== Using the Stargate REST API

If you prefer, you can use Postman as a client interface for exploring REST APIs (https://www.postman.com/downloads/[download here]).
We've provided a https://github.com/stargate/docs/blob/master/modules/developers-guide/examples/stargate-rest-api.postman_collection.json[Stargate REST API Postman Collection] that you can import in Postman to play with the examples shown in this walkthrough.

The steps below use `cURL` to access the REST interface.

=== Generate an auth token

First generate an auth token that is required in each subsequent request
in the `X-Cassandra-Token` header.

NOTE: The port for the authorization service is 8081.

[source,bash]
----
curl -L -X POST 'http://localhost:8081/v1/auth' \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "username": "cassandra",
    "password": "cassandra"
}'
----

Expected output:
[source,bash]
----
{"authToken":"{auth-token}"}
----

Store the authorization token in an environment variable to make it easy to use with `cURL`.

[source,bash]
----
export AUTH_TOKEN={auth-token}
----

Now you can use the REST API.

[source,bash]
----
curl --location --request GET 'localhost:8082/v2/keyspaces' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'accept: application/json' \
--header 'content-type: application/json'
----

=== Creating a keyspace using the REST API

Send a `POST` request to `/v2/schemas/keyspaces`,
in this example we use `users_keyspace` for the `name`,
and `1` for the number of data `replicas`.

[source,bash]
----
curl --location --request POST 'localhost:8082/schemas/keyspaces' \
  --header "X-Cassandra-Token: $AUTH_TOKEN" \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "name": "users_keyspace",
    "replicas": 1
}'
----

=== Creating a table using the REST API

Send a `POST` request to `/v2/schmeas/keyspaces/{keyspace_name}/tables` to create a table. Set the table name and column definitions in the JSON body.

[source,bash]
----
curl --location --request POST 'localhost:8082/schemas/keyspaces/users_keyspace/tables' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "users",
    "columnDefinitions":
      [
        {
          "name": "firstname",
          "typeDefinition": "text"
        },
        {
          "name": "lastname",
          "typeDefinition": "text"
        },
        {
          "name": "email",
          "typeDefinition": "text"
        },
        {
          "name": "favorite color",
          "typeDefinition": "text"
        }
      ],
    "primaryKey":
      {
        "partitionKey": ["firstname"],
        "clusteringKey": ["lastname"]
      },
    "tableOptions":
      {
        "defaultTimeToLive": 0,
        "clusteringExpression":
          [{ "column": "lastname", "order": "ASC" }]
      }
}'
----

=== Write data

Send a `POST` request to `/v2/keyspaces/{keyspace_name}/{table_name}` to add data to the table. The column name/value pairs are passed in the JSON body.

[source,bash]
----
curl --location --request POST 'localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data-raw '{
    "firstname": "Mookie",
    "lastname": "Betts",
    "email": "mookie.betts@gmail.com",
    "favorite color": "blue"
}'
----

Send a `GET` request to `/v2/keyspaces/{keyspace_name}/{table_name}` to retrieve a row using the primary key of the table row.

[source,bash]
----
curl -G --location --request GET 'http://localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data-urlencode 'where={"firstname": {"$eq": "Mookie"}}'
----

=== Update data

To update a row, send a `PUT` request to `/v2/keyspaces/{keyspace_name}/{table_name}/{path}`.
The `{path}` is the primary key values.
In this example the partition key is `firstname` "Mookie" and the clustering key is `lastname` "Betts".

[source,bash]
----
curl --location --request PUT 'localhost:8082/v2/keyspaces/users_keyspace/users/Mookie/Betts' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'content-type: application/json' \
--data-raw '{
"email": "mookie.betts.new-email@gmail.com",
}'

----

NOTE: Updates are upserts. If the row doesn't exist, it will be created. If it does exist, it will be udpated with the new row data.

=== Delete data

To delete a row, send a `DELETE` request to `/v2/keyspaces/{keyspace_name}/{table_name}/{path}`.

[source,bash]
----
curl --location --request DELETE 'localhost:8082/v2/keyspaces/users_keyspace/users/Mookie' \
  --header "X-Cassandra-Token: $AUTH_TOKEN" \
  --header 'accept: application/json' \
  --header 'content-type: application/json'
----

Voila! For more information on the REST API, see the full reference in the REST API section of the docs.
