= 5-minute quick start guide for Stagate

Stargate is a flexible framework for interacting with data stored in Apache Cassandra. Stargate clusters provide different data interfaces above an underlying Cassandra cluster, allowing you to separate your computation needs, represented by the Stargate cluster, from your storage needs, represented by the Cassandra cluster. Developers can focus on the Stargate data interfaces, and let Stargate manage and optimize the connection to the underlying storage.

Stargate by default provides a CQL and REST interface to Cassandra data, with additional plugins available for GraphQL and document store interfaces.

== Prerequisites

To use Stargate you need:
  * A local instance of Apache Cassandra
  ** (optional) Docker if you need to install Cassandra locally on Linux
  ** (optional) https://github.com/riptano/ccm[ccm] if you need to install Cassandra locally on OS X
  * JDK 8 or later
  * Git
  * (optional) `cURL` to run REST queries

=== Installing Apache Cassandra locally using Docker

Install a local Cassandra instance using Docker.

[source,bash]
----
docker run --name local-cassandra \
--net=host \
-e CASSANDRA_CLUSTER_NAME=stargate \
-d cassandra:3.11.6
----

WARNING: Docker for Mac does not work when installing `local-cassandra` on OS X. Use ccm on OS X.

=== Installing Apache Cassandra locally using ccm

Install a local Cassandra instance using `ccm`:

[source,bash]
----
ccm create -v 3.11.6 -b -n 1:0 -i 127.0.0 stargate && ccm start
----

== Building Stargate

In a terminal:

. Clone the https://github.com/stargate/stargate repository:

[source,bash]
----
git clone https://github.com/stargate/stargate
----

. Navigate to the `stargate` directory.

[source,bash]
----
cd stargate
----

. Build Stargate using the `mvnw` command.

[source,bash]
----
./mvnw clean package
----

== Starting Stargate

If you are using Stargate on OS X, add an additional loopback interface:

[source,bash]
----
sudo ifconfig lo0 alias 127.0.0.2
----

Start a local Stargate instance:

[source,bash]
----
./starctl --cluster-name stargate --cluster-seed 127.0.0.1 --cluster-version 3.11 --listen 127.0.0.2 --simple-snitch
----

You can also start Stargate with Docker.

[source,bash]
----
docker build -t stargate . && docker run -i -t stargate
----

By default Stargate starts a CQL service on port 9042 and a REST interface on port 8082.

== Using `cqlsh` to run CQL commands

Connect to the Stargate instance running on 127.0.0.2 on port 9042:

[source,bash]
----
cqlsh 127.0.0.2 9042
----

== Using the Stargate REST interface

Use `cURL` to access the REST interface.

[source,bash]
----
curl -L -X GET 'localhost:8082/v1/health' \
--header 'accept: application/json' \
--header 'content-type: application/json'
----
