= 5-minute quick start guide for Stargate

Stargate is a flexible framework for interacting with data stored in Apache Cassandra^(TM)^.
Stargate clusters provide different data interfaces above an underlying Cassandra cluster, allowing you to separate your computation needs, represented by the Stargate cluster, from your storage needs, represented by the Cassandra cluster.
Developers can focus on the Stargate data interfaces, and let Stargate manage and optimize the connection to the underlying storage.

Stargate by default provides a CQL and REST interface to Cassandra data, with additional plugins available for GraphQL and document store interfaces.

== Prerequisites

To use Stargate you need:

// tag::prereqsList[]
* Docker installed and running
* JDK 8 or later
* `cURL` to run REST queries
// end::prereqsList[]

// == Building Stargate
//
// In a terminal:
//
// . Clone the https://github.com/stargate/stargate repository:
//
// [source,bash]
// ----
// git clone https://github.com/stargate/stargate
// ----
//
// . Navigate to the `stargate` directory.
//
// [source,bash]
// ----
// cd stargate
// ----
//
// . Build Stargate using the `mvnw` command.
//
// [source,bash]
// ----
// ./mvnw clean package
// ----

// tag::getDockerImage[]
== Getting the Stargate Docker image

Pull the Stargate Docker image:

[source,bash,subs="attributes+"]
----
docker pull stargateio/stargate-3_11:{stargate-docker-tag}
----

This image contains the Cassandra Query Language (CQL) and REST APIs with an Apache Cassandra 3.11 backend.

// end::getDockerImage[]

// tag::startDocker[]
== Starting Stargate using Docker

Start the Docker image in developer mode:

[source,bash,subs="attributes+"]
----
docker run --name stargate \
  -p 8081:8081 \
  -p 8082:8082 \
  -p 127.0.0.1:9042:9042 \
  -d \
  -e CLUSTER_NAME=stargate \
  -e CLUSTER_VERSION=3.11 \
  -e DEVELOPER_MODE=true \
  stargateio/stargate-3_11:{stargate-docker-tag}
----

By default Stargate starts a CQL service on port 9042 and a REST interface on port 8082.

// end::startDocker[]

== Using the Stargate REST API

Use `cURL` to access the REST interface. The REST API responds to requests at `{stargate host}:8082/v1` and `{stargate host}:8082/v2`.

Generate an authorization token by calling `/v1/auth` and logging in with the default `cassandra` user.

[source,bash]
----
curl -L -X POST 'http://localhost:8081/v1/auth' \
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "cassandra",
  "password": "cassandra"
}'
----

You should receive a token in the response.

[source,json]
----
{"authToken":"{auth-token}"}
----

Store the authorization token in an environment variable to make it easy to use with `cURL`.

[source,bash]
----
export AUTH_TOKEN={auth-token}
----

Now you can use the REST API.

[source,bash]
----
curl --location --request GET 'localhost:8082/v2/keyspaces' \
  --header "X-Cassandra-Token: $AUTH_TOKEN" \
  --header 'accept: application/json' \
  --header 'content-type: application/json'
----

=== Creating a keyspace using the REST API

Send a `POST` request to `/v2/keyspaces`, setting `name` to the name of the keyspace, and `replicas` to the Cassandra replication factor.

[source,bash]
----
curl --location --request POST 'localhost:8082/schemas/keyspaces' \
  --header "X-Cassandra-Token: $AUTH_TOKEN" \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "name": "users_keyspace",
    "replicas": 1
}'
----

=== Creating a table using the REST API

Send a `POST` request to `/v2/keyspaces/{keyspace_name}/tables` to create a table. Set the table name and column definitions in the JSON body.

[source,bash]
----
curl --location --request POST 'localhost:8082/schemas/keyspaces/users_keyspace/tables' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "users",
    "columnDefinitions":
      [
        {
          "name": "firstname",
          "typeDefinition": "text"
        },
        {
          "name": "lastname",
          "typeDefinition": "text"
        },
        {
          "name": "email",
          "typeDefinition": "text"
        },
        {
          "name": "favorite color",
          "typeDefinition": "text"
        }
      ],
    "primaryKey":
      {
        "partitionKey": ["firstname"],
        "clusteringKey": ["lastname"]
      },
    "tableOptions":
      {
        "defaultTimeToLive": 0,
        "clusteringExpression":
          [{ "column": "lastname", "order": "ASC" }]
      }
}'
----

=== Adding and modifying data using the REST API

Send a `POST` request to `/v2/keyspaces/{keyspace_name}/{table_name}` to add data to the table. Set the column data as name/value pairs in the JSON body.

[source,bash]
----
curl --location --request POST 'localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data-raw '{
    "firstname": "Mookie",
    "lastname": "Betts",
    "email": "mookie.betts@gmail.com",
    "favorite color": "blue"
}'
----

Send a `GET` request to `/v2/keyspaces/{keyspace_name}/{table_name}` and filter on the partition key to retrieve a particular row from the table.

[source,bash]
----
curl -G --location --request GET 'http://localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data-urlencode 'where={"firstname": {"$eq": "Mookie"}}'
----

To retrieve all the rows in a table, send a `GET` request to `/v2/keyspaces/{keyspace_name}/{table_name}`.

[source,bash]
----
curl --request GET \
  --url 'localhost:8082/v2/keyspaces/users_keyspace/users' \
  --header "X-Cassandra-Token: $AUTH_TOKEN" \
  --header 'accept: application/json'
----

To update a row, send a `POST request to `/v2/keyspaces/{keyspace_name}/{table_name}`. Set the column data as name/value pairs in the JSON body.

[source,bash]
----
curl --request POST \
--url 'localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'content-type: application/json' \
--data-raw '{
    "firstname": "Mookie",
    "lastname": "Betts",
    "email": "mookie.betts@gmail.com",
    "favorite color": "red"
}'

----

NOTE: Updates are upserts. If the row doesn't exist, it will be created. If it does exist, it will be udpated with the new row data.

To delete a row, send a `DELETE` request to `/v2/keyspaces/{keyspace_name}/{table_name}`.

[source,bash]
----
curl --request DELETE \
  --url 'localhost:8082/v2/keyspaces/users_keyspace/users' \
  --header "X-Cassandra-Token: $AUTH_TOKEN" \
  --header 'accept: application/json' \
  --header 'content-type: application/json'
----
