= 5-minute quick start guide for Stargate

Stargate is a flexible framework for interacting with data stored in Apache Cassandra. Stargate clusters provide different data interfaces above an underlying Cassandra cluster, allowing you to separate your computation needs, represented by the Stargate cluster, from your storage needs, represented by the Cassandra cluster. Developers can focus on the Stargate data interfaces, and let Stargate manage and optimize the connection to the underlying storage.

Stargate by default provides a CQL and REST interface to Cassandra data, with additional plugins available for GraphQL and document store interfaces.

== Prerequisites

To use Stargate you need:

* A local instance of Apache Cassandra
** (optional) https://github.com/riptano/ccm[ccm] if you need to install Cassandra locally on OS X
* Docker
* JDK 8 or later
* Git
* `cURL` to run REST queries

=== Installing Apache Cassandra locally using Docker

Install a local Cassandra instance using Docker.

[source,bash]
----
docker run --name local-cassandra \
--net=host \
-e CASSANDRA_CLUSTER_NAME=stargate \
-d cassandra:3.11.7
----

WARNING: Docker for Mac does not work when installing `local-cassandra` on OS X. Use ccm on OS X.

=== Installing Apache Cassandra locally using ccm

Install a local Cassandra instance using `ccm`:

[source,bash]
----
ccm create -v 3.11.7 -b -n 1:0 -i 127.0.0 stargate && ccm start
----

// == Building Stargate
//
// In a terminal:
//
// . Clone the https://github.com/stargate/stargate repository:
//
// [source,bash]
// ----
// git clone https://github.com/stargate/stargate
// ----
//
// . Navigate to the `stargate` directory.
//
// [source,bash]
// ----
// cd stargate
// ----
//
// . Build Stargate using the `mvnw` command.
//
// [source,bash]
// ----
// ./mvnw clean package
// ----

== Starting Stargate

If you are using Stargate on OS X, add an additional loopback interface:

[source,bash]
----
sudo ifconfig lo0 alias 127.0.0.2
----

Start a local Stargate instance using Docker:

// [source,bash]
// ----
// ./starctl --cluster-name stargate --cluster-seed 127.0.0.1 --cluster-version 3.11 --listen 127.0.0.2 --simple-snitch
// ----
//
// You can also start Stargate with Docker.

[source,bash]
----
docker run -i -t stargate
----

By default Stargate starts a CQL service on port 9042 and a REST interface on port 8082.

// == Using `cqlsh` to run CQL commands
//
// Connect to the Stargate instance running on 127.0.0.2 on port 9042:
//
// [source,bash]
// ----
// cqlsh 127.0.0.2 9042
// ----

== Using the Stargate REST API

Use `cURL` to access the REST interface. The REST API responds to requests at `{stargate host}:8082/v1`.

[source,bash]
----
curl -L -X GET 'localhost:8082/v2/schemas/keyspaces' \
--header 'accept: application/json' \
--header 'content-type: application/json'
----

=== Creating a keyspace using the REST API

Send a `POST` request to `/v2/schemas/keyspaces`, setting `name` to the name of the keyspace, and `replicas` to the Cassandra replication factor.

[source,bash]
----
curl --request POST \
  --url 'localhost:8082/v2/schemas/keyspaces' \
  --header 'accept: */*' \
  --header 'content-type: application/json' \
  --data '{"name": "betterbotz", "replicas": "2"}'
----

=== Creating a table using the REST API

Send a `POST` request to `/v2/schemas/keyspaces/{keyspace_name}/tables` to create a table. Set the table name and column definitions in the JSON body.

[source,bash]
----
curl --request POST \
  --url 'localhost:8082/v2/schemas/keyspaces/betterbotz/tables' \
  --header 'accept: */*' \
  --header 'content-type: application/json' \
  --data '{"name":"products","ifNotExists":true,"columnDefinitions": [ {"name":"id","typeDefinition":"uuid","static":false}, {"name":"name","typeDefinition":"text","static":false}, {"name":"description","typeDefinition":"text","static":false}, {"name":"price","typeDefinition":"decimal","static":false}, {"name":"created","typeDefinition":"timestamp","static":false}],"primaryKey": {"partitionKey":["id"]},"tableOptions":{"defaultTimeToLive":0}}'
----

=== Adding and modifying data using the REST API

Send a `POST` request to `/v2/schemas/keyspaces/{keyspace_name}/tables/{table_name}/rows` to add data to the table. Set the column data as name/value pairs in the JSON body.

[source,bash]
----
curl --request POST \
  --url 'localhost:8082/v2/schemas/keyspaces/betterbotz/tables/products/rows'
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --data '{"columns":[{"name":"id","value":"e9b6c02d-0604-4bab-a3ea-6a7984654631"},{"name":"name","value":"Heavy Lift Arms"},{"name":"description","value":"Heavy lift arms capable of lifting 1,250 lbs of weight per arm. Sold as a set."},{"name":"price","value":"4199.99"},{"name":"created","value":"2019-01-10 09:48:31.020+0040"}]}'
----

Send a `GET` request to `/v2/schemas/keyspaces/{keyspace_name}/tables/{table_name}/rows/{primary_key}` to retrieve a particular row from the table.

[source,bash]
----
curl --request GET \
  --url 'localhost:8082/v2/schemas/keyspaces/betterbotz/tables/products/rows/e9b6c02d-0604-4bab-a3ea-6a7984654631' \
  --header 'accept: application/json'
----

To retrieve all the rows in a table, send a `GET` request to `/v2/schemas/keyspaces/{keyspace_name}/tables/{table_name}/rows`.

[source,bash]
----
curl --request GET \
  --url 'localhost:8082/v2/schemas/keyspaces/betterbotz/tables/products/rows' \
  --header 'accept: application/json'
----

To update a row, send a `POST request to `/v2/schemas/keyspaces/{keyspace_name}/tables/{table_name}/rows`. Set the column data as name/value pairs in the JSON body.

[source,bash]
----
curl --request POST \
  --url 'localhost:8082/v2/schemas/keyspaces/betterbotz/tables/products/rows' \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --data '{"columns":[{"name":"id","value":"e9b6c02d-0604-4bab-a3ea-6a7984654631"},{"name":"name","value":"Heavy Lift Arms"},{"name":"description","value":"Heavy lift arms capable of lifting 1,250 lbs of weight per arm. Sold as a set."},{"name":"price","value":"9999.99"},{"name":"created","value":"2019-01-10 09:48:31.020+0040"}]}'
----

NOTE: Updates are upserts. If the row doesn't exist, it will be created. If it does exist, it will be udpated with the new row data.

To delete a row, send a `DELETE` request to `/v2/schemas/keyspaces/{keyspace_name}/tables/{table_name}/rows/{primary_key}`.

[source,bash]
----
curl --request DELETE \
  --url 'localhost:8082/v2/schemas/keyspaces/betterbotz/tables/products/rows/e9b6c02d-0604-4bab-a3ea-6a7984654631' \
  --header 'accept: application/json' \
  --header 'content-type: application/json'
----
