= Stargate Document API QuickStart

*Time to complete: 5 minutes*

Stargate is a data gateway deployed between client applications and a database.
In this QuickStart, you'll be up and running on your local machine with the
// LLP: Is it really CRUD access? need to think about this one
Document API plugin that exposes CRUD access to data stored in Cassandra tables.

// tag::prereqsList[]
include::partial$text/prereqs.adoc[]
// end::prereqsList[]

// tag::getDockerImage[]
include::partial$bash/docker_pull.sh[]
// end::getDockerImage[]

// tag::startDocker[]
include::partial$bash/docker_run.sh[]
// end::startDocker[]

== Using the Stargate Document API

In order to use the Stargate Document API, an authorization token must be
generated to access the interface.

// tag::startGenAuthToken[]
include::partial$bash/gen_auth_token.sh[]
// tag::endGenAuthToken[]

// tag::startUseAuthToken[]
Store the auth token in an environment variable to make it easy to use with `cURL`.

[source,bash]
----
export AUTH_TOKEN={auth-token}
----
// tag::endUseAuthToken[]

// tag::startUsingPostman[]
== Using Postman

If you prefer, you can use Postman as a client interface for exploring REST
Document APIs (https://www.postman.com/downloads/[download here]).
// LLP: NEED TO REPLACE THIS
We've provided a
https://github.com/stargate/docs/blob/master/modules/developers-guide/examples/stargate-rest-api.postman_collection.json[Stargate Document API Postman Collection]
that you can import in Postman to play with the examples shown in this walkthrough.

Now you're ready to use the Document API for CRUD operations.
// tag::endUsingPostman[]

== Creating schema

// LLP: NEED TO ADD NAMESPACE/COLLECTION STUFF BEFORE THE KEYSPACE STUFF
// OR REFER KEYSPACE STUFF TO THE REST QS/DOCS

// tag::startCreateNS[]
=== Creating a namespace using the Document API

Send a `POST` request to `/v2/schemas/namespaces`.
In this example we use `fitness` for the `name`,
and `1` for the number of data `replicas`.

[source,bash]
----
curl --location --request POST 'localhost:8082/v2/schemas/namespaces' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "name": "fitness",
    "replicas": 1
}'
----
// tag::endCreateNS[]

// tag::startCreateCollection[]
=== Creating a collection using the Document API

Send a `POST` request to `/v2/schemas/namespace/fitness/collections`.
In this example we use `fitness-data` for the `name`,
and `1` for the number of data `replicas`.

[source,bash]
----
curl --location --request POST 'localhost:8082/v2/schemas/namespace/fitness/collections' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "name": "fitness-data",
    "replicas": 1
}'
----
// tag::endCreateCollection[]

// tag::startCheckNSColl[]
=== Checking that namespaces and collections exist

To check if a namespace or collection exists, execute the REST query with `cURL`:

[source,bash]
----
curl -L -X GET 'localhost:8082/v2/namespaces' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
// LLP: REPLACE
----

For collections:

[source,bash]
----
curl -L -X GET 'localhost:8082/v2/namespaces/'fitness'/collections' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
// LLP: REPLACE
----
// tag::endCheckNSColl[]

// tag::startCreateKS[]
=== Creating a keyspace using the Document API

Send a `POST` request to `/v2/schemas/keyspaces`.
In this example we use `users_keyspace` for the `name`,
and `1` for the number of data `replicas`.

[source,bash]
----
curl --location --request POST 'localhost:8082/v2/schemas/keyspaces' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "name": "users_keyspace",
    "replicas": 1
}'
----
// tag::endCreateKS[]

// tag::startCreateTable[]
=== Creating a table using the Document API

Send a `POST` request to `/v2/schemas/keyspaces/{keyspace_name}/tables` to create a table.
Set the table name and column definitions in the JSON body.

[source,bash]
----
curl --location --request POST 'localhost:8082/v2/schemas/keyspaces/users_keyspace/tables' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
	"name": "users",
	"columnDefinitions":
	  [
        {
	      "name": "firstname",
	      "typeDefinition": "text"
	    },
        {
	      "name": "lastname",
	      "typeDefinition": "text"
	    },
	    {
	      "name": "email",
	      "typeDefinition": "text"
	    },
        {
	      "name": "favorite color",
	      "typeDefinition": "text"
	    }
	  ],
	"primaryKey":
	  {
	    "partitionKey": ["firstname"],
	    "clusteringKey": ["lastname"]
	  },
	"tableOptions":
	  {
	    "defaultTimeToLive": 0,
	    "clusteringExpression":
	      [{ "column": "lastname", "order": "ASC" }]
	  }
}'
----
// tag::endCreateTable[]

// tag::startCheckKSTables[]
=== Checking that keyspaces and tables exist

To check if a keyspace or tables exist, execute the REST query with `cURL`:

[source,bash]
----
curl -L -X GET 'localhost:8082/v2/keyspaces' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
["data_endpoint_auth","users_keyspace","stargate_system","system","system_auth","system_distributed","system_schema","system_traces"]
----

For tables:

[source,bash]
----
curl -L -X GET 'localhost:8082/v2/keyspaces/'users_keyspace'/tables' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'X-Cassandra-Token: $AUTH_TOKEN'
----

returns

[source, plaintext]
----
["users"]
----
// tag::endCheckKSTables[]

== Interacting with tables
// tag::startWriteData[]
=== Write data

Send a `POST` request to `/v2/keyspaces/{keyspace_name}/{table_name}` to add data to the table.
The column name/value pairs are passed in the JSON body.

[source,bash]
----
curl --location --request POST 'localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "firstname": "Mookie",
    "lastname": "Betts",
    "email": "mookie.betts@gmail.com",
    "favorite color": "blue"
}'
----
// tag::endWriteData[]

// tag::startReadData[]
=== Read data

Send a `GET` request to `/v2/keyspaces/{keyspace_name}/{table_name}`
to retrieve a row using the primary key of the table in the `where` params.

[source,bash]
----
curl -G --location 'http://localhost:8082/v2/keyspaces/users_keyspace/users' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data-urlencode 'where={"firstname": {"$eq": "Mookie"}}'
----
// tag::endReadData[]

// tag::startUpdateData[]
=== Update data

To update a row, send a `PUT` request to `/v2/keyspaces/{keyspace_name}/{table_name}/{path}`.
The `{path}` is comprised of the primary key values.
In this example the partition key is `firstname` "Mookie" and the clustering key is `lastname` "Betts"
so we use `/Mookie/Betts` as the `{path}` in our request.

[source,bash]
----
curl --location --request PUT 'localhost:8082/v2/keyspaces/users_keyspace/users/Mookie/Betts' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json' \
--data '{
    "email": "mookie.betts.new-email@email.com"
}'
----

NOTE: Updates are upserts. If the row doesn't exist, it will be created.
If it does exist, it will be udpated with the new row data.

// tag::endUpdateData[]

// tag::startDeleteData[]
=== Delete data
To delete a row, send a `DELETE` request to `/v2/keyspaces/{keyspace_name}/{table_name}/{path}`.
In this request we delete all data with the primary key `firstname` of `Mookie`

[source,bash]
----
curl --location --request DELETE 'localhost:8082/v2/keyspaces/users_keyspace/users/Mookie' \
--header "X-Cassandra-Token: $AUTH_TOKEN" \
--header 'Content-Type: application/json'
----
// tag::endDeleteData[]
Voila! For more information on the Document API, see the xref:developers-guide/openapi_rest_ref.adoc[Document API] in the Data API section.
