= Stargate REST API QuickStart

*Time to complete: 5 minutes*

Stargate is a data gateway deployed between client applications and a database.
In this QuickStart, you'll be up and running on your local machine with the REST API
plugin that exposes CRUD access to data stored in Cassandra tables.

// tag::prereqsList[]
include::developers-guide:partial$prereqs.adoc[]
// end::prereqsList[]

include::developers-guide:partial$astra_tip.adoc[]

// tag::getDockerImage[]
include::developers-guide:partial$docker_pull_3x.adoc[]
// end::getDockerImage[]

// tag::startDocker[]
include::developers-guide:partial$docker_run_3x.adoc[]
// end::startDocker[]

== Using the Auth API to generate an auth token
In order to use the Stargate Document API, an authorization token must be
generated to access the interface.

// generate the auth token
include::developers-guide:partial$gen_auth_token.adoc[]

// using the auth token
include::developers-guide:page$document-using.adoc[tag=UseAuthToken]

// tag::startUsingPostman[]
== Using Postman

If you prefer, you can use Postman as a client interface for exploring REST APIs
(https://www.postman.com/downloads/[download here]).
We've provided a
https://github.com/stargate/docs/blob/master/modules/developers-guide/examples/stargate-rest-api.postman_collection.json[Stargate REST API Postman Collection] that you can import in Postman to play with the examples shown in this walkthrough.

Now you're ready to use the REST API for CRUD operations.
// tag::endUsingPostman[]

== Creating schema

In order to use the REST API, you must create schema that defines the keyspace and
tables that will store the data. A keyspace is a container for which a
`replication factor` defines the number of data replicas the database will store.
Tables consist of columns that have a defined data type. Multiple tables are contained
in a keyspace, but a table cannot be contained in multiple keyspaces.

// create keyspace
include::developers-guide:page$rest-using.adoc[tag=CreateKS]

// check keyspaces exist
include::developers-guide:page$rest-using.adoc[tag=CheckKS]

// create table
include::developers-guide:page$rest-using.adoc[tag=CreateTable]

// check tables and columns exist
include::developers-guide:page$rest-using.adoc[tag=CheckTables]

== Interacting with data stored in tables

// write table data
include::developers-guide:page$rest-using.adoc[tag=WriteData]

// read table data
include::developers-guide:page$rest-using.adoc[tag=ReadData]

// update table data
include::developers-guide:page$rest-using.adoc[tag=UpdateData]

// delete table data
include::developers-guide:page$rest-using.adoc[tag=DeleteData]


Voila! For more information on the REST API, see the see the
xref:developers-guide:rest-using.adoc[Using the REST API]
or the xref:developers-guide:openapi_rest_ref.adoc[REST API] in the
Data API section.
