== Node.js processing result set
:page-tag: stargate,dev,develop

After executing a query a response will be returned containing rows for a SELECT statement,
otherwise the returned payload will be unset.
The convenience function `ToResultSet()`` is provided to help transform this response
into a ResultSet that's easier to work with.

[source, javascript]
----
include::example$javascript/node-processing1.js[]
----

=== Reading primitive values

Individual values from queries will be returned as a `Value` object.
These objects have boolean `hasX()` methods, where X is the possible type of a value.

There are corresponding `getX()` methods on the `Value` type that will return the value, if present.
If the value does not represent type X, calling `getX()` will not return an error.
You'll get `undefined` or another falsy value based on the expected data type.

[source, javascript]
----
include::example$javascript/node-processing-primitive.js[]
----

=== Reading CQL data types

The built-in `toX()` methods for Values representing more complicated types
like UUIDs can be hard to work with.
This library exposes helper functions to translate a Value into a more easily used type:

* toUUIDString
* toCQLTime

Unlike the built-in `toX()` methods, these helper functions will throw an error if the conversion fails.

Here's an example of processing a UUID:

[source, javascript]
----
include::example$javascript/node-processing-cql.js[]
----
