== Rust developing
:page-tag: stargate,dev,develop

=== Building

.Install Rust toolchain:

[source, shell, subs="attributes+"]
----
include::example$bash/rust-build1.sh[]
----

.Run build in the root directory of the project:

[source, shell, subs="attributes+"]
----
include::example$bash/rust-build2.sh[]
----

=== Running the examples

For your convenience, this project contains a bunch of examples located in the
examples directory, which demonstrate connecting, creating schemas,
inserting data and querying.
You'll need a working instance of a Stargate cluster to run the examples.
<<<<<<< HEAD:docs-src/stargate-develop/modules/develop/pages/api-grpc/rust/rust-developing.adoc
Refer to the official https://stargate.io/docs/install/install_overview.html[Stargate Installation documentation]
=======
Refer to the official link: xref:install/install_overview.html[Stargate Installation documentation]
>>>>>>> main:modules/developers-guide/pages/rust-developing.adoc
for more details on how to setup Stargate.

Each example program accepts an URL of the Stargate coordinator,
the authentication token and the keyspace name:

[source, rust]
----
include::example$rust/rust-run-example.rs[]
----

The authentication token value can be also defined in the SG_TOKEN environment variable.

ifeval::["{product}" == "Stargate"]
You'll need to start a Stargate instance.

include::manage:page$start-stargate.adoc[]
endif::[]

==== Run examples

Run the `keyspace` example to test the connection and create the test
keyspace with the default keyspace name of `stargate_examples`:

[tabs]
====
Run test::
+
--
[source, rust]
----
include::example$rust/rust-run-ks-example.rs[]
----
--

Result::
+
--
[source, plaintext]
----
include::example$rust/rust-run-ks-example.result[]
----
--
====

Run the `query` example to create a keyspace and table, insert some data, and
select data to check the insertion:

[tabs]
====
Run test::
+
--
[source, rust]
----
include::example$rust/rust-run-query-example.rs[]
----
--

Result::
+
--
[source, plaintext]
----
include::example$rust/rust-run-query-example.result[]
----
--
====
