=== New Cassandra and Stargate using docker-compose

The `docker-compose` YAML file contains the configuration for pulling the
required docker images and configuration required for installing:

* 1-3 Apache Cassandra^(TM)^ 4.0 nodes as a cluster (backend-1, backend-2, backend-3)
* 1 Stargate node (stargate)

The Stargate image contains the Cassandra Query Language (CQL), REST, Document, GraphQL APIs,
and GraphQL Playground.

Two companion files are helpful: a script to run the docker-compose file with
delays between node startup that prevents timing issues, and a text file that
has the `docker run` commands for running a CQLSH Docker container to query against
either one of the Cassandra nodes or the Stargate node, respectively.

The files are found at the
https://github.com/stargate/docker-images/tree/master/examples/cassandra-4.0[Stargate docker-images repository].

Run the script after downloading the files:

[source,bash,subs="attributes+"]
----
./start_stargate-cass40.sh
----

CAUTION: When Stargate is launched within a container on Mac OS X as shown above,
it will connect only to Cassandra clusters running within the same Docker
environment. To run Stargate so that it can connect to a cluster running outside
of a containerized environment,
see the xref:install_existing_cass_40.adoc[Installing on VMs or bare metal] documentation.
