.Working with graphQL entries
****
Before you start creating types, mutations and queries, it is helpful to
understand that there are four ways to enter mutations and queries:

. In the GraphQL playground, copy and paste the following to a tab pointing to
`{base_gql_url}{base_gql_schema}`:

[source, plaintext, subs="attributes+"]
----
include::example$graphql/createKeyspace.graphql[]
----

[arabic, start=2]
. If you wish to submit the mutation using a curl command, use a JSON file as
the data:

[source, plaintext, subs="attributes+"]
----
include::example$graphql/1curl_createKeyspaceWithFile.sh[]
----

where `createKeyspace.json`:

[source, plaintext, subs="attributes+"]
----
include::example$graphql/createKeyspace.json[]
----

Compare `createKeyspace.json` to the source that you can copy/paste into the
playground, and notice the JSON decoration that is added.

[arabic, start=3]
. If you wish to submit the mutation using a curl command, not using a JSON file,
but directly adding the data, note that the JSON must be entered as a single line
of data.

[source, plaintext, subs="attributes+"]
----
include::example$graphql/1curl_createKeyspace.sh[]
----

[arabic, start=4]
. The last way to create schema is by deploying a schema file, as is shown on this
page in xref:dev-with-graphql-schema-first.adoc#deploy-or-undeploy-schema[Deploy or undeploy schemas].
****
