== Java developing
:page-tag: stargate,dev,develop

=== Generating gRPC code stubs

To see a guide how the Java code is compiled from the proto files see the
link:https://github.com/grpc/grpc-java/blob/master/README.md#download[gRPC setup project dependencies].
To update the protobuf files being used, add the new files to the top level proto
directory and then run make proto from the root of the project.

=== More notes on the asynchronous use of the gRPC API

Up to this point, we were using the blocking version of the generated stub.
We can also interact with the Stargate API using the async version of the stub.
To do so, we need to pass the
link:https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html[StreamObserver]
that will be called asynchronously when the results are available.

Every StreamObserver needs to implement 3 methods: `onNext()`, `onError()` and `onComplete()`.
For example:

[source, java]
----
include::example$java/java-grpc-stream-observer.java[]
----

Please note that this is a very simplified version only for demonstration purposes and should not be used on production.

Once we have the Observer, we can pass it to the `executeQuery` method on the async stub:

[source, java]
----
include::example$java/java-grpc-execute-async.java[]
----

This query will return immediately because it is non-blocking.
If your program (or test) is progressing to the end, you may not be able to see the results.
Your program may exit before the data arrives.
After some time, when the data arrives, the `streamObserver` will be called.

The output of our program will look like this:

[source, yaml]
----
include::example$yaml/async-yaml-result.yaml[]
----

Please note, that at the end we have a `completed` emitted.
This is called by the `onCompleted` method.
