// tag::CreateTable[]
=== Create a table in your keyspace

Create tables in your database using the {company} {database} REST API.
Use the application token you generated to create a table in your keyspace.
A keyspace is like a bucket that holds your tables.
You can create different keyspaces for groups of tables.

=== Prerequisites

. xref:manage:org/managing-org.adoc#manage-application-tokens[Manage application token].
. After generating an authorization token, run the following request to get all available keyspaces
and verify that the keyspace you wish to use is listed in the results:

include::develop:page$api-rest/rest-checking-keyspace.adoc[]

For example, we'll use `{rkeyspace}` as the keyspace.
// ASTRA If the keyspace is not listed, go to your {astra_db} dashboard and add the keyspace.

* Optional: A header line using a `{unique-UUID}`, a randomly-generated UUID that
is unique for the authorization request, can be included in the previous command
by adding the following line:

[source, shell, subs="attributes+"]
----
 --header 'x-cassandra-request-id: {unique-UUID}'
----

// tag::CreateTable[]
=== Create a table

Send a `POST` request to `{base_rest_schema}/{keyspace-name}/tables` to create a table.
Set the table name and column definitions in the JSON body in the `--data` field.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$rest/curl_create_table.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/rest_curl_create_table.result[]
----
--
====

The name of our example table is `{rtable}`.
This table column definition includes:

Partition key::
One or more columns required. `{rpartitionkey}` is the partition key.
Clustering key::
Optional, but zero, one or more columns can be defined. `{rclusteringkey}` is the clustering key.
Non-primary key::
Optional, but zero, one or more columns that are not a partition key or clustering key can be defined.
`favorite_color` is the non-primary key column.

Notice that each column must have a xref:develop:api-rest/rest-data-types.adoc[data type] specified.


// ASTRA
ifdef::astra[]
// Information about primary keys (partition keys and clustering keys) are found in the
// link:https://docs.datastax.com/en/astra-cql/doc/cql/cql_using/wherePK.html
[Cassandra Query Language (CQL) reference, window="_blank"].
endif::[]
// STARGATE
ifdef::stargate[]
Information about partition keys and clustering keys are found in the
https://cassandra.apache.org/doc/latest/cql/[CQL reference].
endif::[]

_Optional:_ Table options can be set.
The two options are:

defaultTimeToLive::
Sets the default Time-To-Live (TTL).
clusteringExpression::
Defines the order, either ascending (`ASC`) or descending (`DESC`) for columns that
are clustering keys. `ASC` is the default.

[source, shell, subs="attributes+"]
----

  "tableOptions":
    {
      "defaultTimeToLive": 0,
      "clusteringExpression":
        [{ "column": "{rclusteringkey}", "order": "ASC" }]
    }
----

// end::CreateTable[]