= gRPC API
:slug: grpc-using

Stargate is a data gateway deployed between client applications and a database.
https://grpc.io/docs/what-is-grpc/introduction/[gRPC] is a modern, open source remote procedure call (RPC) framework.
It enables client and server applications to communicate transparently, and makes it easier to build connected systems.
The Stargate gRPC API is implemented to create language-specific queries
using CQL with any Cassandra deployment.

== Prerequisites

include::develop:partial$prereqs-astra.adoc[]
include::develop:partial$prereqs-stargate.adoc[]

In addition, check out the xref:develop:tooling.adoc#bloomrpc-resources[BloomRPC tool]
that is useful for working with gRPC queries and data.

== API reference

=== Currently supported languages

Four language clients are currently available:

* xref:develop:api-grpc/gRPC-rust-client.adoc[Rust client]
* xref:develop:api-grpc/gRPC-go-client.adoc[Go client]
* xref:develop:api-grpc/gRPC-node-client.adoc[Node.js client]
* xref:develop:api-grpc/gRPC-java-client.adoc[Java client]

// * xref:develop:api-grpc/-client-creation.adoc[Creating new Stargate gRPC clients]