= Developing with the {database} GraphQL API (CQL-first)
:keywords: database, GraphQL, api

include::partial$stargate-intro-intro.adoc[]

The GraphQL API modifies and queries your table data using GraphQL types, queries, and mutations.

For every table in your keyspace, a series of GraphQL objects are generated, along
with queries and mutations for searching and modifying the table data.

include::develop:partial$GQLAPIBlogPost.adoc[]

== Prerequisite

* `cURL` to run REST queries

// ASTRA
ifdef::astra[]

* If you haven't already, create a database using https://astra.datastax.com/[{database}].
* Before you get started, set your environment variables to save time developing on your database.

. In link:https://astra.datastax.com[{database}, window="_blank"], select the database to which you want to connect.
. In your *Database Dashboard*, select *Connect*.
. Select *REST API*.
+
include::develop:partial$note_multi-region_connect.adoc[]

. Follow the steps in the prerequisites to get your xref:manage:org/managing-org.adoc#_manage_application_tokens[application token] and set up your environment variables.
. In your command-line interface associated with your environment, paste the following environment variables copied for your {astra_db} database:

[source, shell]
----
export ASTRA_DB_ID=<database_id>
export ASTRA_DB_REGION=<database_region>
export ASTRA_DB_KEYSPACE=<keyspace_name>
export ASTRA_DB_APPLICATION_TOKEN=<app_token>
----
endif::[]

== About the GraphQL API endpoints

There are two {database} GraphQL API endpoints, one for creating schema and the other
for querying or mutating a keyspace. 
The URLS are:

Schema::
ifdef::astra[]
`{base_graphql_url}/api/graphql-schema`
endif::[]
ifdef::stargate[]
`{base_graphql_url}/graphql-schema`
endif::[]

Querying::
ifdef::astra[]
`{base_graphql_url}/api/graphql/{keyspace_name}`
endif::[]
ifdef::stargate[]
`{base_graphql_url}/graphql/{keyspace_name}`
endif::[]

The schema endpoint is used to create or alter CQL schema in GraphQL cql-first
using direct schema manipulation.
The querying and mutating endpoint is constructed using a particular keyspace name.

Each request must have a valid xref:manage:org/managing-org.adoc#_manage_application_tokens[application token].
Each request can also have an optional unique request id.
The request id is recommended in a production environment and can be useful in troubleshooting issues.

[TIP]
====
**Generating UUIDs**
Consider using a tool like this https://www.uuidgenerator.net/[online UUID generator, window="_blank"]
to quickly create a random UUID to pass with your requests if you are submitting
the queries manually using a tool like cURL.
====

include::develop:partial$GQLNaming.adoc[]

== Mapping {database} tables to GraphQL fields and types in CQL-first

The {database} GraphQL API generates fields and types for each table in your database.
For example, for an {database} table named `book` the following fields and types
are generated.

[source, plaintext,subs="attributes+"]
----
include::develop:example$graphql/cql-first/generatedApi.graphql[]
----

=== Generated query types

The following query types are generated:

* `book()`: Query book values by equality. If no value argument is
provided, then the first hundred (default pagesize) values are returned.
* `bookFilter`: Query book values by filtering the result with additional operators.
For example `gt` (greater than), `lt` (less than), `in` (in a list of values).
The `book()` equality style query is preferable if your queries don't require
non-equality operators.

=== Generated mutation types

The following mutations are generated:

Several mutations are created that you can use to insert, update, or delete books.
Some important facts about these mutations are:

* `insertbook()` is an **upsert** operation if a book with the same information
exist, unless the `ifNotExists` is set to true.
* `updatebook()` is also an **upsert** operation, and will create a new book if
it doesn't exist, unless `ifNotExists` is set to true.
* `deletebook()` will delete a book.
* Using the `ifNotExists` or `ifCondition` options affects the performance of
operations because of the compare-and-set execution path in Cassandra. Under
the hood these operations are using a feature in Cassandra called lightweight
transactions (LWTs).

As more tables are added to your keyspace, additional fields are added to the
query and mutation types to handle queries and mutations for the new tables.

include::page$using-graphql-playground.adoc[]

include::page$tooling.adoc[Using Postman as a tool, tag=using-postman]

// LLP 12.21.21 NEED TO SORT OUT AUTH/APP TOKEN FOR STARGATE AND ASTRA
// SUSPECT THAT manage will be sg in sg docs, and astra in astra-docs

include::page$manage/manage-application-tokens.adoc[Get an application token]

ifdef::stargate[]
include::develop:page$api-graphql-cql-first/gql-creating-keyspace.adoc[Creating keyspace schema]
endif::[]

include::develop:page$api-graphql-cql-first/gql-checking-keyspace.adoc[Checking keyspace schema]

ifdef::stargate[]
include::develop:page$api-graphql-cql-first/gql-deleting-keyspace.adoc[Dropping keyspace schema]
endif::[]

include::develop:page$api-graphql-cql-first/gql-schema-data-types.adoc[Schema and data types]

include::develop:page$api-graphql-cql-first/gql-creating-table.adoc[Creating table schema]

include::develop:page$api-graphql-cql-first/gql-adding-columns.adoc[Adding columns to a table]

include::develop:page$api-graphql-cql-first/gql-checking-table.adoc[Checking table and column schema]

include::develop:page$api-graphql-cql-first/gql-dropping-columns.adoc[Dropping column schema]

include::develop:page$api-graphql-cql-first/gql-dropping-table.adoc[Dropping table schema]

include::develop:page$api-graphql-cql-first/gql-creating-index.adoc[Creating an index]

include::develop:page$api-graphql-cql-first/gql-deleting-index.adoc[Deleting an index]

include::develop:page$api-graphql-cql-first/gql-creating-udt.adoc[Creating a user-defined type (UDT)]

include::develop:page$api-graphql-cql-first/gql-dropping-udt.adoc[Dropping a user-defined type (UDT)]

//include::develop:page$api-graphql-cql-first/graphql-dropping-schema.adoc[Dropping user-defined types (UDTs), tables or columns using GraphQL]

// LLP: 12.22.21 This information is included earlier on this page.
//include::develop:page$api-graphql-cql-first/gql-api-generation.adoc[API generation]

include::develop:page$api-graphql-cql-first/gql-adding-rows.adoc[Adding rows to your table]

include::develop:page$api-graphql-cql-first/gql-retrieving-rows.adoc[Retrieving rows from your table]

include::develop:page$api-graphql-cql-first/gql-updating-rows.adoc[Updating rows in your table]

include::develop:page$api-graphql-cql-first/gql-deleting-rows.adoc[Deleting rows in your table]

