= Developing with the {database} Document API
:keywords: database, document, api

include::develop:partial$stargate-intro-intro.adoc[]
The Stargate Document API modifies and queries data stored as unstructured JSON documents in collections.
Because the Document API uses schemaless data, no data modeling is required!

If the Document API is used with Apache Cassandra, the document indexing is accomplished
with secondary indexes. 
If the Document API is used with DataStax Enterprise, SAI indexing is used. 
The blog https://stargate.io/2020/10/19/the-stargate-cassandra-documents-api.html[The Stargate Cassandra Documents API] describes the underlying structure used to store collections.

== Information about namespaces and collections.

To use the Document API, you must define the namespace that will store  collections.
Collections store unstructured JSON documents.
Documents can themselves hold multiple documents.
Multiple collections are contained in a namespace, but a collection cannot be
contained in multiple namespaces.

Only namespaces need to be specifically created.
Collections are specified when a document is inserted.

== Prerequisites

include::develop:partial$prereqs-astra.adoc[]
include::develop:partial$prereqs-stargate.adoc[]

== API reference
If you prefer to learn using a QuickStart, try out the xref:quickstart:quick_start-document.adoc[Stargate Document QuickStart, window="_blank"].
// LLP 03.16.22 MOVE attachments to develop/attachments
To view the API Reference, see xref:ROOT:attachment$docv2.html[{database} Document API, window="_blank"].

// STARGATE ONLY
ifdef::stargate[]
include::develop:page$api-doc/doc-creating-namespace.adoc[Creating a namespace]
endif::[]

include::develop:page$api-doc/doc-checking-namespace.adoc[Checking for namespace]

// STARGATE ONLY
ifdef::stargate[]
include::develop:page$api-doc/doc-deleting-namespace.adoc[Dropping a namespace]
endif::[]

include::develop:page$api-doc/doc-writing-documents.adoc[Writing documents]

include::develop:page$api-doc/doc-reading-documents.adoc[Reading documents]

include::develop:page$api-doc/doc-updating-documents.adoc[Updating documents]

include::develop:page$api-doc/doc-deleting-documents.adoc[Deleting documents and collections]

// MOVE THIS STUFF TO SDKs and create a page there.
//include::develop:page$api-doc/doc-nodejs-client.adoc[Node.js Collection Client]
