// tag::UpdateBasicData[]
= Updating documents
 
Data changes, so often it is necessary to update or modify an entire document.

== Replace a document with PUT

A `PUT` request using a document-id will replace a document found in a collection.

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-put-replace.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-put-replace.result[]
----
--
====

To check if the data is changed, `GET` the document:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-get-one.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one-2.result[]
----
--
====

== Replace some data in a document with PATCH and document-id

A 'PATCH' request using a document-id will replace the targeted data in a JSON object contained in the document. 
JSON objects are delimited by `{ }` in the data.
If you have an array, delimited by '[ ]' in the JSON object targeted, or a scalar value,
the values will be overwritten.

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-patch.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-patch.result[]
----
--
====

To check if the data is changed, `GET` the document:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-get-one.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one-3.result[]
----
--
====

[WARNING]
====
`PATCH` updates are upserts. If the document doesn't exist, it will be created.
If it does exist, it will be updated with the new document data.
====

== Another example with PATCH

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-patch2.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-patch2.result[]
----
--
====

To check if the data is changed, `GET` the document:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-get-one.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one-4.result[]
----
--
====

// end::UpdateBasicData[]

// tag::UpdateAdvData[]

== Write data to a document-path with PUT

It is also possible to update only part of a document.
Using a `PUT` request, you can replace current data in a document. 
To partially update, send a `PUT` request to
`{base_doc_api}/{namespace_name}/collections/{collections_name}/{document-id}/{document-path}`.
This example will change the book title from `Native Son` to `Native Daughter`:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-put-book-with-path.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-put-book-with-path.result[]
----
--
====

== Write data to a document-path with PATCH

Using a `PATCH` request, you can overwrite current data in a document. 
To partially update, send a `PATCH` request to
`{base_doc_api}/{namespace_name}/collections/{collections_name}/{document-id}/{document-path}`.
This example overwrites a book's information:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-patch-book-with-path.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-patch-book-with-path.result[]
----
--
====

include::develop:page$api-doc/doc-document-push-pop-array.adoc[Using built-in array functions push and pop, leveloffset=+1]

// end::UpdateAdvData[]