= Reading documents
include:develop:escaped-attributes.adoc[]

You can either search in collections for documents, or you can search within documents.

It is possible to get a value for a particular field in a document using one of
two methods, either a `where` clause or a `document-path`. 
These methods canretrieve documents from a collection, or information from within a document.
Both methods will be detailed.

== List all documents in a collection

This command finds all the documents that exist in a collection.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/v2/curl-document-get-all.sh[]
----
--

cURL command (/v1)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/v1/curl-document-get-all.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-all.result[]
----
--
====

include::develop:page$api-doc/doc-document-decorations.adoc[leveloffset=+1]

include::develop:page$api-doc/doc-document-simple-where.adoc[leveloffset=+0]

include::develop:page$api-doc/doc-document-operators.adoc[leveloffset=+1]

== Search collections for documents with other techniques

=== Use multiple fields

Multiple fields can be specified for a search using a comma to delineate the search fields.
For example, a specified value for a city can search in both the primary and secondary addresses of a reader:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/v2/curl-document-get-where-address-city.sh[]
----
--

cURL command (/v1)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/v1/curl-document-get-where-address-city.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-where-address-city.result[]
----
--
====

=== Use a wildcard (*) in a string or array field

A wildcard (*) is useful when searching for a specified value in multiple fields of the same type.
It can be used to search either a string field or an array field.
In this example, several book reviews are searched, looking for a specified book title.
Each reader review has a number of fields, of which `book-title` is one. 

[IMPORTANT]
====
A wildcard *cannot* be used as the last field in a specified path.
====

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/v2/curl-document-get-where-book-eq.sh[]
----
--

cURL command (/v1)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/v1/curl-document-get-where-book-eq.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-where-book-eq.result[]
----
--
====

// LLP, 08.09.22 I HAVE EXAMPLES FOR CONTAINS, BUT THEY DON'T WORK, DUE TO THE 
// WILDCARD CAN'T BE LAST IN PATH - NEED TO CHANGE THEM
// tag::ReadBasicData[]

== Retrieving a document from a collection with a document-id

=== Retrieving a specified document

Let's check that some data was inserted for a particular document.
Send a `GET` request to `{base_doc_api}/\{namespace_name}/collections/\{collection_name}/\{document-id}` to retrieve the document:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/v2/curl-document-get-one.sh[]
----
--

cURL command (/v1)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/v1/curl-document-get-one.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one.result[]
----
--
====

== Search for information within documents

=== Retrieving a specific portion of a document with document-path

A document-path uses a document's structure to drill down and get information from within a document.
To find particular values, send a `GET` request to
`{base_doc_api}/\{namespace_name}/collections/\{collection_name}/\{document-id}/\{document-path}`
to retrieve a book title:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/v2/curl-data-get-path-in-document.sh[]
----
--

cURL command (/v1)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/v1/curl-data-get-path-in-document.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-data-get-path-in-document.result[]
----
--
====

=== Retrieving a document field value using a document-path and array number

This example shows the use of an array value, in conjunction with a document-id and document-path,
to find the book-title of the second book a reader reviewed:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/v2/curl-data-get-path-array-in-document.sh[]
----
--

cURL command (/v1)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/v1/curl-data-get-path-array-in-document.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-data-get-path-array-in-document.result[]
----
--
====

=== Retrieving document data using a document-path and WHERE clause

This example shows the use of a `WHERE` clause, in conjunction with a document-id and document-path:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/v2/curl-data-where-with-document-path.sh[]
----
--

cURL command (/v1)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/v1/curl-data-where-with-document-path.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-data-where-with-document-path.result[]
----
--
====

// tag::ReadAdvData[
// end::ReadAdvData[]
