// tag::WriteBasicData[]
= Writing documents

All data written with the Document API is stored as JSON documents stored in
collections.

include::partial$DocAPIBlogPost.adoc[]

== Add document with a document-id

First, let's add a document to a specified collection using a document-id.
If a document-id is specified, a `PUT` request is required, rather than a `POST` request.
The document-id can be any string.
Send a `PUT` request to `{base_doc_api}/{namespace_name}/collections/{collection_name}/{document-id}` to add data to the collection `{collection}`.
The data is passed in the JSON body.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-put-withDocId.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-put-withDocId.result[]
----
--
====

Notice that the `document-id` is returned.

== Add a document without a document-id

Suppose you want each document to be assigned a random UUID. 
Send a `POST` request to `{base_doc_api}/{namespace_name}/collections/{collections_name}`
to add data to the collection `{collection}`.
The data is passed in the JSON body.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-post-noDocId.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-post-noDocId.result[]
----
--
====

Notice that the `document-id` returned is a UUID if not specified, by default.

== Add a document with data

Documents can be added with varying JSON data, unless a xref:dev-with-doc.adoc#add-JSON-schema-to-a-collection[JSON schema is specified].
Send a `POST` request to `{base_doc_api}/{namespace_name}/collections/{collections_name}` similar to the last example, but add more JSON data to the body of the request:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-post-one-reader.sh[]
----

--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-post-one-reader.result[]
----
--
====

// LLP 97.25.2022 CHECK THIS INFO
// Note the difference between using `POST` and `PUT`. The `POST` request
// is used to insert new documents when you want the system to auto-generate the
// documentId. The `PUT` request is used to insert a new document when you want to
// specify the documentId.

// `PUT` requests can also be used to update an existing
// document. Let's look at those examples, next.

// ############# BIG PATCH WARNING: 
// ############# One thing to note: PATCH expects that the data present at the path is 
// ############# already a JSON object {}. if you have an array or some scalar value, 
// ############# those values will be blown away and overwritten

// end::WriteBasicData[]

// tag::WriteAdvData[]

== Add another document (used in examples)

This document insertion is used in later examples. 
It is a `PUT` request:

[tabs]
====
cURL command (/v2)::
+
.Click to see code
[%collapsible]
=====
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-put-one-book.sh[]
----
--
=====

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-put-one-book.result[]
----
--
====

== Check a document with GET request

You are probably wondering how you get data back from a document. 
Let's read the data from the last example with a `GET` request:

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-get-one-book.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one-book.result[]
----
--
====

== Add documents in a BATCH

It is often convenient to insert several documents into a collection with one request.
The Document API has an endpoint that allows for batches of JSON documents to be inserted
into the same collection.
This feature was added with https://github.com/stargate/stargate/pull/1043[https://github.com/stargate/stargate/pull/1043].


.*More advanced use of batch*
[%collapsible]
====
Data sent to the endpoint `{base_doc_api}/{namespace_name}/collections/{collection_name}/batch` is expected to be in JSON lines format (1 document per line)
// LLP 07.25.2022 DIDN'T I WRITE AN EXAMPLE USING THE ID-PATH? 

Additionally, you can supply an id-path query parameter to use the value at a particular path in each document as the document's key in the database.
So if all your documents have an id field, you could set `id-path=id` and treat the value in id as the document's key. 
You can also use any valid path syntax (globs not allowed), e.g. `id-path=user.emails.[0].id`.

If id-path is excluded, random UUIDs will be assigned to every document, and the response will have the document-ids created corresponding in the same order as the documents were supplied in.
====

[tabs]
====
cURL command (/v2)::
+
.Click to see code
[%collapsible]
=====
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-post-mult-readers.sh[]
----
--
=====

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-post-mult-readers.result[]
----
--
====

== Add more documents in a BATCH (used in examples)

[tabs]
====
cURL command (/v2)::
+
.Click to see code
[%collapsible]
=====
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-post-mult-books.sh[]
----
--
=====

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-post-mult-books.result[]
----
--
====

== Add a reader document with document-id [need in examples]

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-put-one-reader-with-id.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-put-one-reader-with-id.result[]
----
--
====

== Decorations for writing documents: Time-to-live (TTL) and profiling

Both TTL and profiling can be used as options for `POST`, `PUT`, and `PATCH` requests.
TTL will add a time-to-live value in the database, so that the entry will be marked for deletion when the TTL expires.

Profiling will return the CQL that is implemented in the back-end when a request is executed.

=== Profiling

Adding `profile=true` to a request will return the CQL that is executed. For this example, a `PATCH` request, an insertion of data is made, and a deletion of data is done, to change the data written.

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-patch3-profiling.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-patch3-profiling.result[]
----
--
====

To check if the data is changed, `GET` the document:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-get-one.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one-5.result[]
----
--
====

=== TTL

[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-put-ttl.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-put-ttl.result[]
----
--
====

To check if the data is changed, `GET` the document:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-get-one.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one-6.result[]
----
--
====


// ############ DONE TO HERE ##################
// ==== Inserting a sub-document
// You can also insert documents that have nested values, or sub-documents.
// Send a `PUT` request to
// `{base_doc_api}/{namespace_name}/collections/{collections_name}/{document-id}`
// to add data to the existing collection.
// The data is passed in the JSON body.

// [tabs]
// ====
// cURL command (/v2)::
// +
// --
// [source,shell, subs="attributes+"]
// ----
// include::example$docapi/library/curl_put_joey_subdoc.sh[]
// ----
// --

// Result::
// +
// --
// [source,plaintext, subs="attributes+"]
// ----
// include::example$result/docapi/library/curl_put_joey_subdoc.result[]
// ----
// --
// ====
// end::WriteAdvData[]