# MODIFY DOCUMENTS

echo "PATCH some more information into a document using document-id"
./curl-document-patch2.sh.tmp | jq -r '.'
echo "Check that 2nd data is included"
./curl-document-get-one.sh.tmp | jq -r '.'

// tag::UpdateBasicData[]
= Update documents
 
Data changes, so often it is necessary to update or modify an entire document.

== Replace a document with PUT

A `PUT` request using a document-id will replace a document found in a collection.

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-put-replace.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-put-replace.result[]
----
--
====

To check if the data is changed, `GET` the document:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-get-one.sh.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one.result[]
----
--
====

== Replace some data in a document with PATCH and document-id

A 'PATCH' request using a document-id will replace the targeted data in a JSON object contained in the document. 
JSON objects are delimited by `{ }` in the data.
If you have an array, delimited by '[ ]' in the JSON object targeted, or a scalar value,
the values will be overwritten.

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/curl_patch_janet.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_janet.result[]
----
--
====

To check if the data is changed, `GET` the document:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-get-one.sh.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one.result[]
----
--
====

[WARNING]
====
 `PATCH` updates are upserts. If the document doesn't exist, it will be created.
If it does exist, it will be updated with the new document data.
====

== Another example with PATCH

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-patch2.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-patch2.result[]
----
--
====

To check if the data is changed, `GET` the document:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/library/curl-document-get-one.sh.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi/library/curl-document-get-one.result[]
----
--
====

// end::UpdateBasicData[]

// tag::UpdateAdvData[]
== Replace part of of a document or sub-document

It is also possible to update only part of a document. To partially update, send
a `PATCH` request to
 `{base_doc_api}/{namespace_name}/collections/{collections_name}/{document-id}/{document-path}`.
In this example, we want to change just the firstname of the document:

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/curl_patch_partial.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_partial.result[]
----
--
====

and a `GET` will show that only the `weights` has been changed.

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/curl_patch_check_partial.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_check_partial.result[]
----
--
====

To partially update a sub-document,  send a `PATCH` request to
 `{base_doc_api}/{namespace_name}/collections/{collections_name}/{document-id}/{document-path}`
 in the same manner as the last command, but including only sub-document
 information to change and the `document-path` of the sub-document. Include
 all fields that you wish to update.

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/curl_patch_subdoc.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_subdoc.result[]
----
--
====

and a `GET` will show that only the `weights` has been changed.

[tabs]
====
cURL command (/v2)::
+
--
[source, shell, subs="attributes+"]
----
include::example$docapi/curl_patch_check_subdoc.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::example$result/docapi_curl_patch_check_subdoc.result[]
----
--
====

// end::UpdateAdvData[]