name: Run linkinator on a schedul
on:
  schedule:
    - cron: "0 10 * * 2"

jobs:
  reminder:
    runs-on: [ubuntu-latest]
    steps:
      - name: Linkinator
      - uses: gr2m/set-cron-schedule-action@v2
        with:
          token: ${{ secrets.PUBLISH_STARGATE_DOCS }}
          cron: |
            0 10 * * 2
          # optional: set workflow id or file name
          #workflow: my-workflow.yml
          # optional: Defaults to "ci($WORKFLOW_NAME): update cron schedule: $CRON_EXPRESSIONS".
          #           $WORKFLOW_NAME and $CRON_EXPRESSIONS will be replaced.
          message: "Run cron job for linkinator every Tues at 10:00 hrs"
      - run: npm run build:linkinator