name: Run linkinator on a schedule
on:
  schedule:
    - cron: "0 9 * * 1,2,3,4,5"

jobs:
  run_linkinator:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "run linkinator" 
        run: |
          npm run build:linkinator

