name: Run linkinator on a schedul
on:
  schedule:
    - cron: "0 10 20 * 2,3,4"

jobs:
  run_linkinator:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "run linkinator" 
        run: |
          npm run build:linkinator

