name: Run linkinator on a schedule
on:
  schedule:
    - cron: "0,15,30,45 8,12,17 * * 0-7"

jobs:
  run_linkinator:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "run linkinator" 
        run: |
          npm run build:linkinator

